{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='License', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-licensemanager-license.html'),
  '#withBeneficiary':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-licensemanager-license.html#cfn-licensemanager-license-beneficiary', args=[d.arg(name='beneficiary', type=d.T.string)]),
  withBeneficiary(beneficiary): { Properties+: { Beneficiary: beneficiary } },
  '#withConsumptionConfiguration':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-licensemanager-license.html#cfn-licensemanager-license-consumptionconfiguration', args=[d.arg(name='consumptionConfiguration', type=d.T.string)]),
  withConsumptionConfiguration(consumptionConfiguration): { Properties+: { ConsumptionConfiguration: consumptionConfiguration } },
  '#withEntitlements':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-licensemanager-license.html#cfn-licensemanager-license-entitlements', args=[d.arg(name='entitlements', type=d.T.string)]),
  withEntitlements(entitlements): { Properties+: { Entitlements: entitlements } },
  '#withHomeRegion':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-licensemanager-license.html#cfn-licensemanager-license-homeregion', args=[d.arg(name='homeRegion', type=d.T.string)]),
  withHomeRegion(homeRegion): { Properties+: { HomeRegion: homeRegion } },
  '#withIssuer':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-licensemanager-license.html#cfn-licensemanager-license-issuer', args=[d.arg(name='issuer', type=d.T.string)]),
  withIssuer(issuer): { Properties+: { Issuer: issuer } },
  '#withLicenseMetadata':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-licensemanager-license.html#cfn-licensemanager-license-licensemetadata', args=[d.arg(name='licenseMetadata', type=d.T.string)]),
  withLicenseMetadata(licenseMetadata): { Properties+: { LicenseMetadata: licenseMetadata } },
  '#withLicenseName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-licensemanager-license.html#cfn-licensemanager-license-licensename', args=[d.arg(name='licenseName', type=d.T.string)]),
  withLicenseName(licenseName): { Properties+: { LicenseName: licenseName } },
  '#withProductName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-licensemanager-license.html#cfn-licensemanager-license-productname', args=[d.arg(name='productName', type=d.T.string)]),
  withProductName(productName): { Properties+: { ProductName: productName } },
  '#withProductSKU':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-licensemanager-license.html#cfn-licensemanager-license-productsku', args=[d.arg(name='productSku', type=d.T.string)]),
  withProductSKU(productSku): { Properties+: { ProductSKU: productSku } },
  '#withStatus':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-licensemanager-license.html#cfn-licensemanager-license-status', args=[d.arg(name='status', type=d.T.string)]),
  withStatus(status): { Properties+: { Status: status } },
  '#withValidity':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-licensemanager-license.html#cfn-licensemanager-license-validity', args=[d.arg(name='validity', type=d.T.string)]),
  withValidity(validity): { Properties+: { Validity: validity } },
}
