(import '../../../extensions/attributes.libsonnet') + {
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='PackagingConfiguration', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediapackage-packagingconfiguration.html'),
  new(errorOnEmptyProp=true): { Type: 'AWS::MediaPackage::PackagingConfiguration', Properties: { PackagingGroupId: if errorOnEmptyProp then (error 'You need to define PackagingGroupId properties for AWS::MediaPackage::PackagingConfiguration resource') else null, Id: if errorOnEmptyProp then (error 'You need to define Id properties for AWS::MediaPackage::PackagingConfiguration resource') else null } },
  '#new':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediapackage-packagingconfiguration.html', args=[d.arg(name='errorOnEmptyProp', type=d.T.bool)]),
  '#withCmafPackage':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediapackage-packagingconfiguration.html#cfn-mediapackage-packagingconfiguration-cmafpackage', args=[d.arg(name='cmafPackage', type=d.T.object)]),
  withCmafPackage(cmafPackage): { Properties+: { CmafPackage: cmafPackage } },
  '#withCmafPackageMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediapackage-packagingconfiguration.html#cfn-mediapackage-packagingconfiguration-cmafpackage', args=[d.arg(name='cmafPackage', type=d.T.object)]),
  withCmafPackageMixin(cmafPackage): { Properties+: { CmafPackage+: cmafPackage } },
  '#withDashPackage':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediapackage-packagingconfiguration.html#cfn-mediapackage-packagingconfiguration-dashpackage', args=[d.arg(name='dashPackage', type=d.T.object)]),
  withDashPackage(dashPackage): { Properties+: { DashPackage: dashPackage } },
  '#withDashPackageMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediapackage-packagingconfiguration.html#cfn-mediapackage-packagingconfiguration-dashpackage', args=[d.arg(name='dashPackage', type=d.T.object)]),
  withDashPackageMixin(dashPackage): { Properties+: { DashPackage+: dashPackage } },
  '#withHlsPackage':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediapackage-packagingconfiguration.html#cfn-mediapackage-packagingconfiguration-hlspackage', args=[d.arg(name='hlsPackage', type=d.T.object)]),
  withHlsPackage(hlsPackage): { Properties+: { HlsPackage: hlsPackage } },
  '#withHlsPackageMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediapackage-packagingconfiguration.html#cfn-mediapackage-packagingconfiguration-hlspackage', args=[d.arg(name='hlsPackage', type=d.T.object)]),
  withHlsPackageMixin(hlsPackage): { Properties+: { HlsPackage+: hlsPackage } },
  '#withId':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediapackage-packagingconfiguration.html#cfn-mediapackage-packagingconfiguration-id', args=[d.arg(name='id', type=d.T.string)]),
  withId(id): { Properties+: { Id: id } },
  '#withMssPackage':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediapackage-packagingconfiguration.html#cfn-mediapackage-packagingconfiguration-msspackage', args=[d.arg(name='mssPackage', type=d.T.object)]),
  withMssPackage(mssPackage): { Properties+: { MssPackage: mssPackage } },
  '#withMssPackageMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediapackage-packagingconfiguration.html#cfn-mediapackage-packagingconfiguration-msspackage', args=[d.arg(name='mssPackage', type=d.T.object)]),
  withMssPackageMixin(mssPackage): { Properties+: { MssPackage+: mssPackage } },
  '#withPackagingGroupId':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediapackage-packagingconfiguration.html#cfn-mediapackage-packagingconfiguration-packaginggroupid', args=[d.arg(name='packagingGroupId', type=d.T.string)]),
  withPackagingGroupId(packagingGroupId): { Properties+: { PackagingGroupId: packagingGroupId } },
  '#withTags':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediapackage-packagingconfiguration.html#cfn-mediapackage-packagingconfiguration-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTags(tags): { Properties+: { Tags: tags } },
  '#withTagsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediapackage-packagingconfiguration.html#cfn-mediapackage-packagingconfiguration-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTagsMixin(tags): { Properties+: { Tags+: tags } },
}
