{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='Pinpoint', url='', help=''),
  ADMChannel: (import '/output/github.com/jsonnet-libs/cloudformation-libsonnet/44.00/_gen/AWS/Pinpoint/ADMChannel.libsonnet'),
  APNSChannel: (import '/output/github.com/jsonnet-libs/cloudformation-libsonnet/44.00/_gen/AWS/Pinpoint/APNSChannel.libsonnet'),
  APNSSandboxChannel: (import '/output/github.com/jsonnet-libs/cloudformation-libsonnet/44.00/_gen/AWS/Pinpoint/APNSSandboxChannel.libsonnet'),
  APNSVoipChannel: (import '/output/github.com/jsonnet-libs/cloudformation-libsonnet/44.00/_gen/AWS/Pinpoint/APNSVoipChannel.libsonnet'),
  APNSVoipSandboxChannel: (import '/output/github.com/jsonnet-libs/cloudformation-libsonnet/44.00/_gen/AWS/Pinpoint/APNSVoipSandboxChannel.libsonnet'),
  App: (import '/output/github.com/jsonnet-libs/cloudformation-libsonnet/44.00/_gen/AWS/Pinpoint/App.libsonnet'),
  ApplicationSettings: (import '/output/github.com/jsonnet-libs/cloudformation-libsonnet/44.00/_gen/AWS/Pinpoint/ApplicationSettings.libsonnet'),
  BaiduChannel: (import '/output/github.com/jsonnet-libs/cloudformation-libsonnet/44.00/_gen/AWS/Pinpoint/BaiduChannel.libsonnet'),
  Campaign: (import '/output/github.com/jsonnet-libs/cloudformation-libsonnet/44.00/_gen/AWS/Pinpoint/Campaign.libsonnet'),
  EmailChannel: (import '/output/github.com/jsonnet-libs/cloudformation-libsonnet/44.00/_gen/AWS/Pinpoint/EmailChannel.libsonnet'),
  EmailTemplate: (import '/output/github.com/jsonnet-libs/cloudformation-libsonnet/44.00/_gen/AWS/Pinpoint/EmailTemplate.libsonnet'),
  EventStream: (import '/output/github.com/jsonnet-libs/cloudformation-libsonnet/44.00/_gen/AWS/Pinpoint/EventStream.libsonnet'),
  GCMChannel: (import '/output/github.com/jsonnet-libs/cloudformation-libsonnet/44.00/_gen/AWS/Pinpoint/GCMChannel.libsonnet'),
  PushTemplate: (import '/output/github.com/jsonnet-libs/cloudformation-libsonnet/44.00/_gen/AWS/Pinpoint/PushTemplate.libsonnet'),
  SMSChannel: (import '/output/github.com/jsonnet-libs/cloudformation-libsonnet/44.00/_gen/AWS/Pinpoint/SMSChannel.libsonnet'),
  Segment: (import '/output/github.com/jsonnet-libs/cloudformation-libsonnet/44.00/_gen/AWS/Pinpoint/Segment.libsonnet'),
  SmsTemplate: (import '/output/github.com/jsonnet-libs/cloudformation-libsonnet/44.00/_gen/AWS/Pinpoint/SmsTemplate.libsonnet'),
  VoiceChannel: (import '/output/github.com/jsonnet-libs/cloudformation-libsonnet/44.00/_gen/AWS/Pinpoint/VoiceChannel.libsonnet'),
}
