{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='AWS.Lambda.Function', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html'),
  '#withArchitectures':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-architectures', args=[d.arg(name='architectures', type=d.T.string)]),
  withArchitectures(architectures): { Properties+: { Architectures: architectures } },
  '#withCode':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-code', args=[d.arg(name='code', type=d.T.string)]),
  withCode(code): { Properties+: { Code: code } },
  '#withCodeSigningConfigArn':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-codesigningconfigarn', args=[d.arg(name='codeSigningConfigArn', type=d.T.string)]),
  withCodeSigningConfigArn(codeSigningConfigArn): { Properties+: { CodeSigningConfigArn: codeSigningConfigArn } },
  '#withDeadLetterConfig':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-deadletterconfig', args=[d.arg(name='deadLetterConfig', type=d.T.string)]),
  withDeadLetterConfig(deadLetterConfig): { Properties+: { DeadLetterConfig: deadLetterConfig } },
  '#withDescription':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-description', args=[d.arg(name='description', type=d.T.string)]),
  withDescription(description): { Properties+: { Description: description } },
  '#withEnvironment':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-environment', args=[d.arg(name='environment', type=d.T.string)]),
  withEnvironment(environment): { Properties+: { Environment: environment } },
  '#withFileSystemConfigs':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-filesystemconfigs', args=[d.arg(name='fileSystemConfigs', type=d.T.string)]),
  withFileSystemConfigs(fileSystemConfigs): { Properties+: { FileSystemConfigs: fileSystemConfigs } },
  '#withFunctionName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-functionname', args=[d.arg(name='functionName', type=d.T.string)]),
  withFunctionName(functionName): { Properties+: { FunctionName: functionName } },
  '#withHandler':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-handler', args=[d.arg(name='handler', type=d.T.string)]),
  withHandler(handler): { Properties+: { Handler: handler } },
  '#withImageConfig':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-imageconfig', args=[d.arg(name='imageConfig', type=d.T.string)]),
  withImageConfig(imageConfig): { Properties+: { ImageConfig: imageConfig } },
  '#withKmsKeyArn':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-kmskeyarn', args=[d.arg(name='kmsKeyArn', type=d.T.string)]),
  withKmsKeyArn(kmsKeyArn): { Properties+: { KmsKeyArn: kmsKeyArn } },
  '#withLayers':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-layers', args=[d.arg(name='layers', type=d.T.string)]),
  withLayers(layers): { Properties+: { Layers: layers } },
  '#withMemorySize':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-memorysize', args=[d.arg(name='memorySize', type=d.T.string)]),
  withMemorySize(memorySize): { Properties+: { MemorySize: memorySize } },
  '#withPackageType':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-packagetype', args=[d.arg(name='packageType', type=d.T.string)]),
  withPackageType(packageType): { Properties+: { PackageType: packageType } },
  '#withReservedConcurrentExecutions':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-reservedconcurrentexecutions', args=[d.arg(name='reservedConcurrentExecutions', type=d.T.string)]),
  withReservedConcurrentExecutions(reservedConcurrentExecutions): { Properties+: { ReservedConcurrentExecutions: reservedConcurrentExecutions } },
  '#withRole':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-role', args=[d.arg(name='role', type=d.T.string)]),
  withRole(role): { Properties+: { Role: role } },
  '#withRuntime':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-runtime', args=[d.arg(name='runtime', type=d.T.string)]),
  withRuntime(runtime): { Properties+: { Runtime: runtime } },
  '#withTags':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-tags', args=[d.arg(name='tags', type=d.T.string)]),
  withTags(tags): { Properties+: { Tags: tags } },
  '#withTimeout':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-timeout', args=[d.arg(name='timeout', type=d.T.string)]),
  withTimeout(timeout): { Properties+: { Timeout: timeout } },
  '#withTracingConfig':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-tracingconfig', args=[d.arg(name='tracingConfig', type=d.T.string)]),
  withTracingConfig(tracingConfig): { Properties+: { TracingConfig: tracingConfig } },
  '#withVpcConfig':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-vpcconfig', args=[d.arg(name='vpcConfig', type=d.T.string)]),
  withVpcConfig(vpcConfig): { Properties+: { VpcConfig: vpcConfig } },
}
