(import '../../../extensions/attributes.libsonnet') + {
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='GraphQLApi', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-graphqlapi.html'),
  new(errorOnEmptyProp=true): { Type: 'AWS::AppSync::GraphQLApi', Properties: { Name: if errorOnEmptyProp then (error 'You need to define Name properties for AWS::AppSync::GraphQLApi resource') else null, AuthenticationType: if errorOnEmptyProp then (error 'You need to define AuthenticationType properties for AWS::AppSync::GraphQLApi resource') else null } },
  '#new':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-graphqlapi.html', args=[d.arg(name='errorOnEmptyProp', type=d.T.bool)]),
  '#withAdditionalAuthenticationProviders':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-graphqlapi.html#cfn-appsync-graphqlapi-additionalauthenticationproviders', args=[d.arg(name='additionalAuthenticationProviders', type=d.T.object)]),
  withAdditionalAuthenticationProviders(additionalAuthenticationProviders): { Properties+: { AdditionalAuthenticationProviders: additionalAuthenticationProviders } },
  '#withAdditionalAuthenticationProvidersMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-graphqlapi.html#cfn-appsync-graphqlapi-additionalauthenticationproviders', args=[d.arg(name='additionalAuthenticationProviders', type=d.T.object)]),
  withAdditionalAuthenticationProvidersMixin(additionalAuthenticationProviders): { Properties+: { AdditionalAuthenticationProviders+: additionalAuthenticationProviders } },
  '#withAuthenticationType':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-graphqlapi.html#cfn-appsync-graphqlapi-authenticationtype', args=[d.arg(name='authenticationType', type=d.T.string)]),
  withAuthenticationType(authenticationType): { Properties+: { AuthenticationType: authenticationType } },
  '#withLambdaAuthorizerConfig':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-graphqlapi.html#cfn-appsync-graphqlapi-lambdaauthorizerconfig', args=[d.arg(name='lambdaAuthorizerConfig', type=d.T.object)]),
  withLambdaAuthorizerConfig(lambdaAuthorizerConfig): { Properties+: { LambdaAuthorizerConfig: lambdaAuthorizerConfig } },
  '#withLambdaAuthorizerConfigMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-graphqlapi.html#cfn-appsync-graphqlapi-lambdaauthorizerconfig', args=[d.arg(name='lambdaAuthorizerConfig', type=d.T.object)]),
  withLambdaAuthorizerConfigMixin(lambdaAuthorizerConfig): { Properties+: { LambdaAuthorizerConfig+: lambdaAuthorizerConfig } },
  '#withLogConfig':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-graphqlapi.html#cfn-appsync-graphqlapi-logconfig', args=[d.arg(name='logConfig', type=d.T.object)]),
  withLogConfig(logConfig): { Properties+: { LogConfig: logConfig } },
  '#withLogConfigMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-graphqlapi.html#cfn-appsync-graphqlapi-logconfig', args=[d.arg(name='logConfig', type=d.T.object)]),
  withLogConfigMixin(logConfig): { Properties+: { LogConfig+: logConfig } },
  '#withName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-graphqlapi.html#cfn-appsync-graphqlapi-name', args=[d.arg(name='name', type=d.T.string)]),
  withName(name): { Properties+: { Name: name } },
  '#withOpenIDConnectConfig':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-graphqlapi.html#cfn-appsync-graphqlapi-openidconnectconfig', args=[d.arg(name='openIdconnectConfig', type=d.T.object)]),
  withOpenIDConnectConfig(openIdconnectConfig): { Properties+: { OpenIDConnectConfig: openIdconnectConfig } },
  '#withOpenIDConnectConfigMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-graphqlapi.html#cfn-appsync-graphqlapi-openidconnectconfig', args=[d.arg(name='openIdconnectConfig', type=d.T.object)]),
  withOpenIDConnectConfigMixin(openIdconnectConfig): { Properties+: { OpenIDConnectConfig+: openIdconnectConfig } },
  '#withTags':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-graphqlapi.html#cfn-appsync-graphqlapi-tags', args=[d.arg(name='tags', type=d.T.object)]),
  withTags(tags): { Properties+: { Tags: tags } },
  '#withTagsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-graphqlapi.html#cfn-appsync-graphqlapi-tags', args=[d.arg(name='tags', type=d.T.object)]),
  withTagsMixin(tags): { Properties+: { Tags+: tags } },
  '#withUserPoolConfig':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-graphqlapi.html#cfn-appsync-graphqlapi-userpoolconfig', args=[d.arg(name='userPoolConfig', type=d.T.object)]),
  withUserPoolConfig(userPoolConfig): { Properties+: { UserPoolConfig: userPoolConfig } },
  '#withUserPoolConfigMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-graphqlapi.html#cfn-appsync-graphqlapi-userpoolconfig', args=[d.arg(name='userPoolConfig', type=d.T.object)]),
  withUserPoolConfigMixin(userPoolConfig): { Properties+: { UserPoolConfig+: userPoolConfig } },
  '#withXrayEnabled':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-graphqlapi.html#cfn-appsync-graphqlapi-xrayenabled', args=[d.arg(name='xrayEnabled', type=d.T.bool)]),
  withXrayEnabled(xrayEnabled): { Properties+: { XrayEnabled: xrayEnabled } },
}
