{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='AWS.PinpointEmail.ConfigurationSet', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-pinpointemail-configurationset.html'),
  '#withDeliveryOptions':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-pinpointemail-configurationset.html#cfn-pinpointemail-configurationset-deliveryoptions', args=[d.arg(name='deliveryOptions', type=d.T.string)]),
  withDeliveryOptions(deliveryOptions): { Properties+: { DeliveryOptions: deliveryOptions } },
  '#withName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-pinpointemail-configurationset.html#cfn-pinpointemail-configurationset-name', args=[d.arg(name='name', type=d.T.string)]),
  withName(name): { Properties+: { Name: name } },
  '#withReputationOptions':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-pinpointemail-configurationset.html#cfn-pinpointemail-configurationset-reputationoptions', args=[d.arg(name='reputationOptions', type=d.T.string)]),
  withReputationOptions(reputationOptions): { Properties+: { ReputationOptions: reputationOptions } },
  '#withSendingOptions':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-pinpointemail-configurationset.html#cfn-pinpointemail-configurationset-sendingoptions', args=[d.arg(name='sendingOptions', type=d.T.string)]),
  withSendingOptions(sendingOptions): { Properties+: { SendingOptions: sendingOptions } },
  '#withTags':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-pinpointemail-configurationset.html#cfn-pinpointemail-configurationset-tags', args=[d.arg(name='tags', type=d.T.string)]),
  withTags(tags): { Properties+: { Tags: tags } },
  '#withTrackingOptions':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-pinpointemail-configurationset.html#cfn-pinpointemail-configurationset-trackingoptions', args=[d.arg(name='trackingOptions', type=d.T.string)]),
  withTrackingOptions(trackingOptions): { Properties+: { TrackingOptions: trackingOptions } },
}
