(import '../../../extensions/attributes.libsonnet') + {
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='AnomalyDetector', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-anomalydetector.html'),
  new(errorOnEmptyProp=true): { Type: 'AWS::CloudWatch::AnomalyDetector', Properties: { Stat: if errorOnEmptyProp then (error 'You need to define Stat properties for AWS::CloudWatch::AnomalyDetector resource') else null, MetricName: if errorOnEmptyProp then (error 'You need to define MetricName properties for AWS::CloudWatch::AnomalyDetector resource') else null, Namespace: if errorOnEmptyProp then (error 'You need to define Namespace properties for AWS::CloudWatch::AnomalyDetector resource') else null } },
  '#new':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-anomalydetector.html', args=[d.arg(name='errorOnEmptyProp', type=d.T.bool)]),
  '#withConfiguration':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-anomalydetector.html#cfn-cloudwatch-anomalydetector-configuration', args=[d.arg(name='configuration', type=d.T.object)]),
  withConfiguration(configuration): { Properties+: { Configuration: configuration } },
  '#withConfigurationMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-anomalydetector.html#cfn-cloudwatch-anomalydetector-configuration', args=[d.arg(name='configuration', type=d.T.object)]),
  withConfigurationMixin(configuration): { Properties+: { Configuration+: configuration } },
  '#withDimensions':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-anomalydetector.html#cfn-cloudwatch-anomalydetector-dimensions', args=[d.arg(name='dimensions', type=d.T.array)]),
  withDimensions(dimensions): { Properties+: { Dimensions: dimensions } },
  '#withDimensionsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-anomalydetector.html#cfn-cloudwatch-anomalydetector-dimensions', args=[d.arg(name='dimensions', type=d.T.array)]),
  withDimensionsMixin(dimensions): { Properties+: { Dimensions+: dimensions } },
  '#withMetricName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-anomalydetector.html#cfn-cloudwatch-anomalydetector-metricname', args=[d.arg(name='metricName', type=d.T.string)]),
  withMetricName(metricName): { Properties+: { MetricName: metricName } },
  '#withNamespace':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-anomalydetector.html#cfn-cloudwatch-anomalydetector-namespace', args=[d.arg(name='namespace', type=d.T.string)]),
  withNamespace(namespace): { Properties+: { Namespace: namespace } },
  '#withStat':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-anomalydetector.html#cfn-cloudwatch-anomalydetector-stat', args=[d.arg(name='stat', type=d.T.string)]),
  withStat(stat): { Properties+: { Stat: stat } },
}
