(import '../../../extensions/attributes.libsonnet') + {
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='Bucket', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lightsail-bucket.html'),
  new(errorOnEmptyProp=true): { Type: 'AWS::Lightsail::Bucket', Properties: { BucketName: if errorOnEmptyProp then (error 'You need to define BucketName properties for AWS::Lightsail::Bucket resource') else null, BundleId: if errorOnEmptyProp then (error 'You need to define BundleId properties for AWS::Lightsail::Bucket resource') else null } },
  '#new':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lightsail-bucket.html', args=[d.arg(name='errorOnEmptyProp', type=d.T.bool)]),
  '#withAccessRules':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lightsail-bucket.html#cfn-lightsail-bucket-accessrules', args=[d.arg(name='accessRules', type=d.T.object)]),
  withAccessRules(accessRules): { Properties+: { AccessRules: accessRules } },
  '#withAccessRulesMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lightsail-bucket.html#cfn-lightsail-bucket-accessrules', args=[d.arg(name='accessRules', type=d.T.object)]),
  withAccessRulesMixin(accessRules): { Properties+: { AccessRules+: accessRules } },
  '#withBucketName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lightsail-bucket.html#cfn-lightsail-bucket-bucketname', args=[d.arg(name='bucketName', type=d.T.string)]),
  withBucketName(bucketName): { Properties+: { BucketName: bucketName } },
  '#withBundleId':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lightsail-bucket.html#cfn-lightsail-bucket-bundleid', args=[d.arg(name='bundleId', type=d.T.string)]),
  withBundleId(bundleId): { Properties+: { BundleId: bundleId } },
  '#withObjectVersioning':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lightsail-bucket.html#cfn-lightsail-bucket-objectversioning', args=[d.arg(name='objectVersioning', type=d.T.bool)]),
  withObjectVersioning(objectVersioning): { Properties+: { ObjectVersioning: objectVersioning } },
  '#withReadOnlyAccessAccounts':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lightsail-bucket.html#cfn-lightsail-bucket-readonlyaccessaccounts', args=[d.arg(name='readOnlyAccessAccounts', type=d.T.array)]),
  withReadOnlyAccessAccounts(readOnlyAccessAccounts): { Properties+: { ReadOnlyAccessAccounts: readOnlyAccessAccounts } },
  '#withReadOnlyAccessAccountsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lightsail-bucket.html#cfn-lightsail-bucket-readonlyaccessaccounts', args=[d.arg(name='readOnlyAccessAccounts', type=d.T.array)]),
  withReadOnlyAccessAccountsMixin(readOnlyAccessAccounts): { Properties+: { ReadOnlyAccessAccounts+: readOnlyAccessAccounts } },
  '#withResourcesReceivingAccess':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lightsail-bucket.html#cfn-lightsail-bucket-resourcesreceivingaccess', args=[d.arg(name='resourcesReceivingAccess', type=d.T.array)]),
  withResourcesReceivingAccess(resourcesReceivingAccess): { Properties+: { ResourcesReceivingAccess: resourcesReceivingAccess } },
  '#withResourcesReceivingAccessMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lightsail-bucket.html#cfn-lightsail-bucket-resourcesreceivingaccess', args=[d.arg(name='resourcesReceivingAccess', type=d.T.array)]),
  withResourcesReceivingAccessMixin(resourcesReceivingAccess): { Properties+: { ResourcesReceivingAccess+: resourcesReceivingAccess } },
  '#withTags':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lightsail-bucket.html#cfn-lightsail-bucket-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTags(tags): { Properties+: { Tags: tags } },
  '#withTagsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lightsail-bucket.html#cfn-lightsail-bucket-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTagsMixin(tags): { Properties+: { Tags+: tags } },
}
