{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='AWS.CloudFormation', url='', help=''),
  CustomResource: (import '/output/github.com/jsonnet-libs/cloudformation-libsonnet/44.00/_gen/AWS/CloudFormation/CustomResource.libsonnet'),
  Macro: (import '/output/github.com/jsonnet-libs/cloudformation-libsonnet/44.00/_gen/AWS/CloudFormation/Macro.libsonnet'),
  ModuleDefaultVersion: (import '/output/github.com/jsonnet-libs/cloudformation-libsonnet/44.00/_gen/AWS/CloudFormation/ModuleDefaultVersion.libsonnet'),
  ModuleVersion: (import '/output/github.com/jsonnet-libs/cloudformation-libsonnet/44.00/_gen/AWS/CloudFormation/ModuleVersion.libsonnet'),
  PublicTypeVersion: (import '/output/github.com/jsonnet-libs/cloudformation-libsonnet/44.00/_gen/AWS/CloudFormation/PublicTypeVersion.libsonnet'),
  Publisher: (import '/output/github.com/jsonnet-libs/cloudformation-libsonnet/44.00/_gen/AWS/CloudFormation/Publisher.libsonnet'),
  ResourceDefaultVersion: (import '/output/github.com/jsonnet-libs/cloudformation-libsonnet/44.00/_gen/AWS/CloudFormation/ResourceDefaultVersion.libsonnet'),
  ResourceVersion: (import '/output/github.com/jsonnet-libs/cloudformation-libsonnet/44.00/_gen/AWS/CloudFormation/ResourceVersion.libsonnet'),
  Stack: (import '/output/github.com/jsonnet-libs/cloudformation-libsonnet/44.00/_gen/AWS/CloudFormation/Stack.libsonnet'),
  StackSet: (import '/output/github.com/jsonnet-libs/cloudformation-libsonnet/44.00/_gen/AWS/CloudFormation/StackSet.libsonnet'),
  TypeActivation: (import '/output/github.com/jsonnet-libs/cloudformation-libsonnet/44.00/_gen/AWS/CloudFormation/TypeActivation.libsonnet'),
  WaitCondition: (import '/output/github.com/jsonnet-libs/cloudformation-libsonnet/44.00/_gen/AWS/CloudFormation/WaitCondition.libsonnet'),
  WaitConditionHandle: (import '/output/github.com/jsonnet-libs/cloudformation-libsonnet/44.00/_gen/AWS/CloudFormation/WaitConditionHandle.libsonnet'),
}
