(import '../../../extensions/attributes.libsonnet') + {
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='TypeActivation', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-typeactivation.html'),
  new(errorOnEmptyProp=true): { Type: 'AWS::CloudFormation::TypeActivation', Properties: {} },
  '#new':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-typeactivation.html', args=[d.arg(name='errorOnEmptyProp', type=d.T.bool)]),
  '#withAutoUpdate':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-typeactivation.html#cfn-cloudformation-typeactivation-autoupdate', args=[d.arg(name='autoUpdate', type=d.T.bool)]),
  withAutoUpdate(autoUpdate): { Properties+: { AutoUpdate: autoUpdate } },
  '#withExecutionRoleArn':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-typeactivation.html#cfn-cloudformation-typeactivation-executionrolearn', args=[d.arg(name='executionRoleArn', type=d.T.string)]),
  withExecutionRoleArn(executionRoleArn): { Properties+: { ExecutionRoleArn: executionRoleArn } },
  '#withLoggingConfig':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-typeactivation.html#cfn-cloudformation-typeactivation-loggingconfig', args=[d.arg(name='loggingConfig', type=d.T.object)]),
  withLoggingConfig(loggingConfig): { Properties+: { LoggingConfig: loggingConfig } },
  '#withLoggingConfigMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-typeactivation.html#cfn-cloudformation-typeactivation-loggingconfig', args=[d.arg(name='loggingConfig', type=d.T.object)]),
  withLoggingConfigMixin(loggingConfig): { Properties+: { LoggingConfig+: loggingConfig } },
  '#withMajorVersion':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-typeactivation.html#cfn-cloudformation-typeactivation-majorversion', args=[d.arg(name='majorVersion', type=d.T.string)]),
  withMajorVersion(majorVersion): { Properties+: { MajorVersion: majorVersion } },
  '#withPublicTypeArn':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-typeactivation.html#cfn-cloudformation-typeactivation-publictypearn', args=[d.arg(name='publicTypeArn', type=d.T.string)]),
  withPublicTypeArn(publicTypeArn): { Properties+: { PublicTypeArn: publicTypeArn } },
  '#withPublisherId':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-typeactivation.html#cfn-cloudformation-typeactivation-publisherid', args=[d.arg(name='publisherId', type=d.T.string)]),
  withPublisherId(publisherId): { Properties+: { PublisherId: publisherId } },
  '#withType':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-typeactivation.html#cfn-cloudformation-typeactivation-type', args=[d.arg(name='type', type=d.T.string)]),
  withType(type): { Properties+: { Type: type } },
  '#withTypeName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-typeactivation.html#cfn-cloudformation-typeactivation-typename', args=[d.arg(name='typeName', type=d.T.string)]),
  withTypeName(typeName): { Properties+: { TypeName: typeName } },
  '#withTypeNameAlias':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-typeactivation.html#cfn-cloudformation-typeactivation-typenamealias', args=[d.arg(name='typeNameAlias', type=d.T.string)]),
  withTypeNameAlias(typeNameAlias): { Properties+: { TypeNameAlias: typeNameAlias } },
  '#withVersionBump':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-typeactivation.html#cfn-cloudformation-typeactivation-versionbump', args=[d.arg(name='versionBump', type=d.T.string)]),
  withVersionBump(versionBump): { Properties+: { VersionBump: versionBump } },
}
