(import '../../../extensions/attributes.libsonnet') + {
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='Domain', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html'),
  new(errorOnEmptyProp=true): { Type: 'AWS::Elasticsearch::Domain', Properties: {} },
  '#new':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html', args=[d.arg(name='errorOnEmptyProp', type=d.T.bool)]),
  '#withAccessPolicies':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html#cfn-elasticsearch-domain-accesspolicies', args=[d.arg(name='accessPolicies', type=d.T.object)]),
  withAccessPolicies(accessPolicies): { Properties+: { AccessPolicies: accessPolicies } },
  '#withAccessPoliciesMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html#cfn-elasticsearch-domain-accesspolicies', args=[d.arg(name='accessPolicies', type=d.T.object)]),
  withAccessPoliciesMixin(accessPolicies): { Properties+: { AccessPolicies+: accessPolicies } },
  '#withAdvancedOptions':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html#cfn-elasticsearch-domain-advancedoptions', args=[d.arg(name='advancedOptions', type=d.T.object)]),
  withAdvancedOptions(advancedOptions): { Properties+: { AdvancedOptions: advancedOptions } },
  '#withAdvancedOptionsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html#cfn-elasticsearch-domain-advancedoptions', args=[d.arg(name='advancedOptions', type=d.T.object)]),
  withAdvancedOptionsMixin(advancedOptions): { Properties+: { AdvancedOptions+: advancedOptions } },
  '#withAdvancedSecurityOptions':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html#cfn-elasticsearch-domain-advancedsecurityoptions', args=[d.arg(name='advancedSecurityOptions', type=d.T.object)]),
  withAdvancedSecurityOptions(advancedSecurityOptions): { Properties+: { AdvancedSecurityOptions: advancedSecurityOptions } },
  '#withAdvancedSecurityOptionsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html#cfn-elasticsearch-domain-advancedsecurityoptions', args=[d.arg(name='advancedSecurityOptions', type=d.T.object)]),
  withAdvancedSecurityOptionsMixin(advancedSecurityOptions): { Properties+: { AdvancedSecurityOptions+: advancedSecurityOptions } },
  '#withCognitoOptions':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html#cfn-elasticsearch-domain-cognitooptions', args=[d.arg(name='cognitoOptions', type=d.T.object)]),
  withCognitoOptions(cognitoOptions): { Properties+: { CognitoOptions: cognitoOptions } },
  '#withCognitoOptionsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html#cfn-elasticsearch-domain-cognitooptions', args=[d.arg(name='cognitoOptions', type=d.T.object)]),
  withCognitoOptionsMixin(cognitoOptions): { Properties+: { CognitoOptions+: cognitoOptions } },
  '#withDomainEndpointOptions':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html#cfn-elasticsearch-domain-domainendpointoptions', args=[d.arg(name='domainEndpointOptions', type=d.T.object)]),
  withDomainEndpointOptions(domainEndpointOptions): { Properties+: { DomainEndpointOptions: domainEndpointOptions } },
  '#withDomainEndpointOptionsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html#cfn-elasticsearch-domain-domainendpointoptions', args=[d.arg(name='domainEndpointOptions', type=d.T.object)]),
  withDomainEndpointOptionsMixin(domainEndpointOptions): { Properties+: { DomainEndpointOptions+: domainEndpointOptions } },
  '#withDomainName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html#cfn-elasticsearch-domain-domainname', args=[d.arg(name='domainName', type=d.T.string)]),
  withDomainName(domainName): { Properties+: { DomainName: domainName } },
  '#withEBSOptions':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html#cfn-elasticsearch-domain-ebsoptions', args=[d.arg(name='ebsoptions', type=d.T.object)]),
  withEBSOptions(ebsoptions): { Properties+: { EBSOptions: ebsoptions } },
  '#withEBSOptionsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html#cfn-elasticsearch-domain-ebsoptions', args=[d.arg(name='ebsoptions', type=d.T.object)]),
  withEBSOptionsMixin(ebsoptions): { Properties+: { EBSOptions+: ebsoptions } },
  '#withElasticsearchClusterConfig':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html#cfn-elasticsearch-domain-elasticsearchclusterconfig', args=[d.arg(name='elasticsearchClusterConfig', type=d.T.object)]),
  withElasticsearchClusterConfig(elasticsearchClusterConfig): { Properties+: { ElasticsearchClusterConfig: elasticsearchClusterConfig } },
  '#withElasticsearchClusterConfigMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html#cfn-elasticsearch-domain-elasticsearchclusterconfig', args=[d.arg(name='elasticsearchClusterConfig', type=d.T.object)]),
  withElasticsearchClusterConfigMixin(elasticsearchClusterConfig): { Properties+: { ElasticsearchClusterConfig+: elasticsearchClusterConfig } },
  '#withElasticsearchVersion':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html#cfn-elasticsearch-domain-elasticsearchversion', args=[d.arg(name='elasticsearchVersion', type=d.T.string)]),
  withElasticsearchVersion(elasticsearchVersion): { Properties+: { ElasticsearchVersion: elasticsearchVersion } },
  '#withEncryptionAtRestOptions':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html#cfn-elasticsearch-domain-encryptionatrestoptions', args=[d.arg(name='encryptionAtRestOptions', type=d.T.object)]),
  withEncryptionAtRestOptions(encryptionAtRestOptions): { Properties+: { EncryptionAtRestOptions: encryptionAtRestOptions } },
  '#withEncryptionAtRestOptionsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html#cfn-elasticsearch-domain-encryptionatrestoptions', args=[d.arg(name='encryptionAtRestOptions', type=d.T.object)]),
  withEncryptionAtRestOptionsMixin(encryptionAtRestOptions): { Properties+: { EncryptionAtRestOptions+: encryptionAtRestOptions } },
  '#withLogPublishingOptions':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html#cfn-elasticsearch-domain-logpublishingoptions', args=[d.arg(name='logPublishingOptions', type=d.T.object)]),
  withLogPublishingOptions(logPublishingOptions): { Properties+: { LogPublishingOptions: logPublishingOptions } },
  '#withLogPublishingOptionsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html#cfn-elasticsearch-domain-logpublishingoptions', args=[d.arg(name='logPublishingOptions', type=d.T.object)]),
  withLogPublishingOptionsMixin(logPublishingOptions): { Properties+: { LogPublishingOptions+: logPublishingOptions } },
  '#withNodeToNodeEncryptionOptions':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html#cfn-elasticsearch-domain-nodetonodeencryptionoptions', args=[d.arg(name='nodeToNodeEncryptionOptions', type=d.T.object)]),
  withNodeToNodeEncryptionOptions(nodeToNodeEncryptionOptions): { Properties+: { NodeToNodeEncryptionOptions: nodeToNodeEncryptionOptions } },
  '#withNodeToNodeEncryptionOptionsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html#cfn-elasticsearch-domain-nodetonodeencryptionoptions', args=[d.arg(name='nodeToNodeEncryptionOptions', type=d.T.object)]),
  withNodeToNodeEncryptionOptionsMixin(nodeToNodeEncryptionOptions): { Properties+: { NodeToNodeEncryptionOptions+: nodeToNodeEncryptionOptions } },
  '#withSnapshotOptions':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html#cfn-elasticsearch-domain-snapshotoptions', args=[d.arg(name='snapshotOptions', type=d.T.object)]),
  withSnapshotOptions(snapshotOptions): { Properties+: { SnapshotOptions: snapshotOptions } },
  '#withSnapshotOptionsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html#cfn-elasticsearch-domain-snapshotoptions', args=[d.arg(name='snapshotOptions', type=d.T.object)]),
  withSnapshotOptionsMixin(snapshotOptions): { Properties+: { SnapshotOptions+: snapshotOptions } },
  '#withTags':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html#cfn-elasticsearch-domain-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTags(tags): { Properties+: { Tags: tags } },
  '#withTagsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html#cfn-elasticsearch-domain-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTagsMixin(tags): { Properties+: { Tags+: tags } },
  '#withVPCOptions':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html#cfn-elasticsearch-domain-vpcoptions', args=[d.arg(name='vpcoptions', type=d.T.object)]),
  withVPCOptions(vpcoptions): { Properties+: { VPCOptions: vpcoptions } },
  '#withVPCOptionsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html#cfn-elasticsearch-domain-vpcoptions', args=[d.arg(name='vpcoptions', type=d.T.object)]),
  withVPCOptionsMixin(vpcoptions): { Properties+: { VPCOptions+: vpcoptions } },
}
