(import '../../../extensions/attributes.libsonnet') + {
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='Endpoint', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html'),
  new(errorOnEmptyProp=true): { Type: 'AWS::DMS::Endpoint', Properties: { EngineName: if errorOnEmptyProp then (error 'You need to define EngineName properties for AWS::DMS::Endpoint resource') else null, EndpointType: if errorOnEmptyProp then (error 'You need to define EndpointType properties for AWS::DMS::Endpoint resource') else null } },
  '#new':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html', args=[d.arg(name='errorOnEmptyProp', type=d.T.bool)]),
  '#withCertificateArn':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-certificatearn', args=[d.arg(name='certificateArn', type=d.T.string)]),
  withCertificateArn(certificateArn): { Properties+: { CertificateArn: certificateArn } },
  '#withDatabaseName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-databasename', args=[d.arg(name='databaseName', type=d.T.string)]),
  withDatabaseName(databaseName): { Properties+: { DatabaseName: databaseName } },
  '#withDocDbSettings':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-docdbsettings', args=[d.arg(name='docDbSettings', type=d.T.object)]),
  withDocDbSettings(docDbSettings): { Properties+: { DocDbSettings: docDbSettings } },
  '#withDocDbSettingsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-docdbsettings', args=[d.arg(name='docDbSettings', type=d.T.object)]),
  withDocDbSettingsMixin(docDbSettings): { Properties+: { DocDbSettings+: docDbSettings } },
  '#withDynamoDbSettings':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-dynamodbsettings', args=[d.arg(name='dynamoDbSettings', type=d.T.object)]),
  withDynamoDbSettings(dynamoDbSettings): { Properties+: { DynamoDbSettings: dynamoDbSettings } },
  '#withDynamoDbSettingsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-dynamodbsettings', args=[d.arg(name='dynamoDbSettings', type=d.T.object)]),
  withDynamoDbSettingsMixin(dynamoDbSettings): { Properties+: { DynamoDbSettings+: dynamoDbSettings } },
  '#withElasticsearchSettings':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-elasticsearchsettings', args=[d.arg(name='elasticsearchSettings', type=d.T.object)]),
  withElasticsearchSettings(elasticsearchSettings): { Properties+: { ElasticsearchSettings: elasticsearchSettings } },
  '#withElasticsearchSettingsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-elasticsearchsettings', args=[d.arg(name='elasticsearchSettings', type=d.T.object)]),
  withElasticsearchSettingsMixin(elasticsearchSettings): { Properties+: { ElasticsearchSettings+: elasticsearchSettings } },
  '#withEndpointIdentifier':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-endpointidentifier', args=[d.arg(name='endpointIdentifier', type=d.T.string)]),
  withEndpointIdentifier(endpointIdentifier): { Properties+: { EndpointIdentifier: endpointIdentifier } },
  '#withEndpointType':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-endpointtype', args=[d.arg(name='endpointType', type=d.T.string)]),
  withEndpointType(endpointType): { Properties+: { EndpointType: endpointType } },
  '#withEngineName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-enginename', args=[d.arg(name='engineName', type=d.T.string)]),
  withEngineName(engineName): { Properties+: { EngineName: engineName } },
  '#withExtraConnectionAttributes':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-extraconnectionattributes', args=[d.arg(name='extraConnectionAttributes', type=d.T.string)]),
  withExtraConnectionAttributes(extraConnectionAttributes): { Properties+: { ExtraConnectionAttributes: extraConnectionAttributes } },
  '#withGcpMySQLSettings':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-gcpmysqlsettings', args=[d.arg(name='gcpMySqlsettings', type=d.T.object)]),
  withGcpMySQLSettings(gcpMySqlsettings): { Properties+: { GcpMySQLSettings: gcpMySqlsettings } },
  '#withGcpMySQLSettingsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-gcpmysqlsettings', args=[d.arg(name='gcpMySqlsettings', type=d.T.object)]),
  withGcpMySQLSettingsMixin(gcpMySqlsettings): { Properties+: { GcpMySQLSettings+: gcpMySqlsettings } },
  '#withIbmDb2Settings':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-ibmdb2settings', args=[d.arg(name='ibmDb2settings', type=d.T.object)]),
  withIbmDb2Settings(ibmDb2settings): { Properties+: { IbmDb2Settings: ibmDb2settings } },
  '#withIbmDb2SettingsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-ibmdb2settings', args=[d.arg(name='ibmDb2settings', type=d.T.object)]),
  withIbmDb2SettingsMixin(ibmDb2settings): { Properties+: { IbmDb2Settings+: ibmDb2settings } },
  '#withKafkaSettings':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-kafkasettings', args=[d.arg(name='kafkaSettings', type=d.T.object)]),
  withKafkaSettings(kafkaSettings): { Properties+: { KafkaSettings: kafkaSettings } },
  '#withKafkaSettingsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-kafkasettings', args=[d.arg(name='kafkaSettings', type=d.T.object)]),
  withKafkaSettingsMixin(kafkaSettings): { Properties+: { KafkaSettings+: kafkaSettings } },
  '#withKinesisSettings':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-kinesissettings', args=[d.arg(name='kinesisSettings', type=d.T.object)]),
  withKinesisSettings(kinesisSettings): { Properties+: { KinesisSettings: kinesisSettings } },
  '#withKinesisSettingsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-kinesissettings', args=[d.arg(name='kinesisSettings', type=d.T.object)]),
  withKinesisSettingsMixin(kinesisSettings): { Properties+: { KinesisSettings+: kinesisSettings } },
  '#withKmsKeyId':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-kmskeyid', args=[d.arg(name='kmsKeyId', type=d.T.string)]),
  withKmsKeyId(kmsKeyId): { Properties+: { KmsKeyId: kmsKeyId } },
  '#withMicrosoftSqlServerSettings':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-microsoftsqlserversettings', args=[d.arg(name='microsoftSqlServerSettings', type=d.T.object)]),
  withMicrosoftSqlServerSettings(microsoftSqlServerSettings): { Properties+: { MicrosoftSqlServerSettings: microsoftSqlServerSettings } },
  '#withMicrosoftSqlServerSettingsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-microsoftsqlserversettings', args=[d.arg(name='microsoftSqlServerSettings', type=d.T.object)]),
  withMicrosoftSqlServerSettingsMixin(microsoftSqlServerSettings): { Properties+: { MicrosoftSqlServerSettings+: microsoftSqlServerSettings } },
  '#withMongoDbSettings':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-mongodbsettings', args=[d.arg(name='mongoDbSettings', type=d.T.object)]),
  withMongoDbSettings(mongoDbSettings): { Properties+: { MongoDbSettings: mongoDbSettings } },
  '#withMongoDbSettingsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-mongodbsettings', args=[d.arg(name='mongoDbSettings', type=d.T.object)]),
  withMongoDbSettingsMixin(mongoDbSettings): { Properties+: { MongoDbSettings+: mongoDbSettings } },
  '#withMySqlSettings':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-mysqlsettings', args=[d.arg(name='mySqlSettings', type=d.T.object)]),
  withMySqlSettings(mySqlSettings): { Properties+: { MySqlSettings: mySqlSettings } },
  '#withMySqlSettingsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-mysqlsettings', args=[d.arg(name='mySqlSettings', type=d.T.object)]),
  withMySqlSettingsMixin(mySqlSettings): { Properties+: { MySqlSettings+: mySqlSettings } },
  '#withNeptuneSettings':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-neptunesettings', args=[d.arg(name='neptuneSettings', type=d.T.object)]),
  withNeptuneSettings(neptuneSettings): { Properties+: { NeptuneSettings: neptuneSettings } },
  '#withNeptuneSettingsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-neptunesettings', args=[d.arg(name='neptuneSettings', type=d.T.object)]),
  withNeptuneSettingsMixin(neptuneSettings): { Properties+: { NeptuneSettings+: neptuneSettings } },
  '#withOracleSettings':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-oraclesettings', args=[d.arg(name='oracleSettings', type=d.T.object)]),
  withOracleSettings(oracleSettings): { Properties+: { OracleSettings: oracleSettings } },
  '#withOracleSettingsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-oraclesettings', args=[d.arg(name='oracleSettings', type=d.T.object)]),
  withOracleSettingsMixin(oracleSettings): { Properties+: { OracleSettings+: oracleSettings } },
  '#withPassword':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-password', args=[d.arg(name='password', type=d.T.string)]),
  withPassword(password): { Properties+: { Password: password } },
  '#withPort':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-port', args=[d.arg(name='port', type=d.T.number)]),
  withPort(port): { Properties+: { Port: port } },
  '#withPostgreSqlSettings':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-postgresqlsettings', args=[d.arg(name='postgreSqlSettings', type=d.T.object)]),
  withPostgreSqlSettings(postgreSqlSettings): { Properties+: { PostgreSqlSettings: postgreSqlSettings } },
  '#withPostgreSqlSettingsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-postgresqlsettings', args=[d.arg(name='postgreSqlSettings', type=d.T.object)]),
  withPostgreSqlSettingsMixin(postgreSqlSettings): { Properties+: { PostgreSqlSettings+: postgreSqlSettings } },
  '#withRedisSettings':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-redissettings', args=[d.arg(name='redisSettings', type=d.T.object)]),
  withRedisSettings(redisSettings): { Properties+: { RedisSettings: redisSettings } },
  '#withRedisSettingsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-redissettings', args=[d.arg(name='redisSettings', type=d.T.object)]),
  withRedisSettingsMixin(redisSettings): { Properties+: { RedisSettings+: redisSettings } },
  '#withRedshiftSettings':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-redshiftsettings', args=[d.arg(name='redshiftSettings', type=d.T.object)]),
  withRedshiftSettings(redshiftSettings): { Properties+: { RedshiftSettings: redshiftSettings } },
  '#withRedshiftSettingsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-redshiftsettings', args=[d.arg(name='redshiftSettings', type=d.T.object)]),
  withRedshiftSettingsMixin(redshiftSettings): { Properties+: { RedshiftSettings+: redshiftSettings } },
  '#withResourceIdentifier':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-resourceidentifier', args=[d.arg(name='resourceIdentifier', type=d.T.string)]),
  withResourceIdentifier(resourceIdentifier): { Properties+: { ResourceIdentifier: resourceIdentifier } },
  '#withS3Settings':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-s3settings', args=[d.arg(name='s3settings', type=d.T.object)]),
  withS3Settings(s3settings): { Properties+: { S3Settings: s3settings } },
  '#withS3SettingsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-s3settings', args=[d.arg(name='s3settings', type=d.T.object)]),
  withS3SettingsMixin(s3settings): { Properties+: { S3Settings+: s3settings } },
  '#withServerName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-servername', args=[d.arg(name='serverName', type=d.T.string)]),
  withServerName(serverName): { Properties+: { ServerName: serverName } },
  '#withSslMode':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-sslmode', args=[d.arg(name='sslMode', type=d.T.string)]),
  withSslMode(sslMode): { Properties+: { SslMode: sslMode } },
  '#withSybaseSettings':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-sybasesettings', args=[d.arg(name='sybaseSettings', type=d.T.object)]),
  withSybaseSettings(sybaseSettings): { Properties+: { SybaseSettings: sybaseSettings } },
  '#withSybaseSettingsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-sybasesettings', args=[d.arg(name='sybaseSettings', type=d.T.object)]),
  withSybaseSettingsMixin(sybaseSettings): { Properties+: { SybaseSettings+: sybaseSettings } },
  '#withTags':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTags(tags): { Properties+: { Tags: tags } },
  '#withTagsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTagsMixin(tags): { Properties+: { Tags+: tags } },
  '#withUsername':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-username', args=[d.arg(name='username', type=d.T.string)]),
  withUsername(username): { Properties+: { Username: username } },
}
