{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='AWS.SageMaker.ModelExplainabilityJobDefinition', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-modelexplainabilityjobdefinition.html'),
  '#withJobDefinitionName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-modelexplainabilityjobdefinition.html#cfn-sagemaker-modelexplainabilityjobdefinition-jobdefinitionname', args=[d.arg(name='jobDefinitionName', type=d.T.string)]),
  withJobDefinitionName(jobDefinitionName): { Properties+: { JobDefinitionName: jobDefinitionName } },
  '#withJobResources':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-modelexplainabilityjobdefinition.html#cfn-sagemaker-modelexplainabilityjobdefinition-jobresources', args=[d.arg(name='jobResources', type=d.T.string)]),
  withJobResources(jobResources): { Properties+: { JobResources: jobResources } },
  '#withModelExplainabilityAppSpecification':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-modelexplainabilityjobdefinition.html#cfn-sagemaker-modelexplainabilityjobdefinition-modelexplainabilityappspecification', args=[d.arg(name='modelExplainabilityAppSpecification', type=d.T.string)]),
  withModelExplainabilityAppSpecification(modelExplainabilityAppSpecification): { Properties+: { ModelExplainabilityAppSpecification: modelExplainabilityAppSpecification } },
  '#withModelExplainabilityBaselineConfig':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-modelexplainabilityjobdefinition.html#cfn-sagemaker-modelexplainabilityjobdefinition-modelexplainabilitybaselineconfig', args=[d.arg(name='modelExplainabilityBaselineConfig', type=d.T.string)]),
  withModelExplainabilityBaselineConfig(modelExplainabilityBaselineConfig): { Properties+: { ModelExplainabilityBaselineConfig: modelExplainabilityBaselineConfig } },
  '#withModelExplainabilityJobInput':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-modelexplainabilityjobdefinition.html#cfn-sagemaker-modelexplainabilityjobdefinition-modelexplainabilityjobinput', args=[d.arg(name='modelExplainabilityJobInput', type=d.T.string)]),
  withModelExplainabilityJobInput(modelExplainabilityJobInput): { Properties+: { ModelExplainabilityJobInput: modelExplainabilityJobInput } },
  '#withModelExplainabilityJobOutputConfig':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-modelexplainabilityjobdefinition.html#cfn-sagemaker-modelexplainabilityjobdefinition-modelexplainabilityjoboutputconfig', args=[d.arg(name='modelExplainabilityJobOutputConfig', type=d.T.string)]),
  withModelExplainabilityJobOutputConfig(modelExplainabilityJobOutputConfig): { Properties+: { ModelExplainabilityJobOutputConfig: modelExplainabilityJobOutputConfig } },
  '#withNetworkConfig':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-modelexplainabilityjobdefinition.html#cfn-sagemaker-modelexplainabilityjobdefinition-networkconfig', args=[d.arg(name='networkConfig', type=d.T.string)]),
  withNetworkConfig(networkConfig): { Properties+: { NetworkConfig: networkConfig } },
  '#withRoleArn':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-modelexplainabilityjobdefinition.html#cfn-sagemaker-modelexplainabilityjobdefinition-rolearn', args=[d.arg(name='roleArn', type=d.T.string)]),
  withRoleArn(roleArn): { Properties+: { RoleArn: roleArn } },
  '#withStoppingCondition':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-modelexplainabilityjobdefinition.html#cfn-sagemaker-modelexplainabilityjobdefinition-stoppingcondition', args=[d.arg(name='stoppingCondition', type=d.T.string)]),
  withStoppingCondition(stoppingCondition): { Properties+: { StoppingCondition: stoppingCondition } },
  '#withTags':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-modelexplainabilityjobdefinition.html#cfn-sagemaker-modelexplainabilityjobdefinition-tags', args=[d.arg(name='tags', type=d.T.string)]),
  withTags(tags): { Properties+: { Tags: tags } },
}
