(import '../../../extensions/attributes.libsonnet') + {
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='NotebookInstanceLifecycleConfig', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-notebookinstancelifecycleconfig.html'),
  new(errorOnEmptyProp=true): { Type: 'AWS::SageMaker::NotebookInstanceLifecycleConfig', Properties: {} },
  '#new':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-notebookinstancelifecycleconfig.html', args=[d.arg(name='errorOnEmptyProp', type=d.T.bool)]),
  '#withNotebookInstanceLifecycleConfigName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-notebookinstancelifecycleconfig.html#cfn-sagemaker-notebookinstancelifecycleconfig-notebookinstancelifecycleconfigname', args=[d.arg(name='notebookInstanceLifecycleConfigName', type=d.T.string)]),
  withNotebookInstanceLifecycleConfigName(notebookInstanceLifecycleConfigName): { Properties+: { NotebookInstanceLifecycleConfigName: notebookInstanceLifecycleConfigName } },
  '#withOnCreate':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-notebookinstancelifecycleconfig.html#cfn-sagemaker-notebookinstancelifecycleconfig-oncreate', args=[d.arg(name='onCreate', type=d.T.array)]),
  withOnCreate(onCreate): { Properties+: { OnCreate: onCreate } },
  '#withOnCreateMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-notebookinstancelifecycleconfig.html#cfn-sagemaker-notebookinstancelifecycleconfig-oncreate', args=[d.arg(name='onCreate', type=d.T.array)]),
  withOnCreateMixin(onCreate): { Properties+: { OnCreate+: onCreate } },
  '#withOnStart':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-notebookinstancelifecycleconfig.html#cfn-sagemaker-notebookinstancelifecycleconfig-onstart', args=[d.arg(name='onStart', type=d.T.array)]),
  withOnStart(onStart): { Properties+: { OnStart: onStart } },
  '#withOnStartMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-notebookinstancelifecycleconfig.html#cfn-sagemaker-notebookinstancelifecycleconfig-onstart', args=[d.arg(name='onStart', type=d.T.array)]),
  withOnStartMixin(onStart): { Properties+: { OnStart+: onStart } },
}
