{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='StateMachine', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html'),
  '#withDefinition':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html#cfn-stepfunctions-statemachine-definition', args=[d.arg(name='definition', type=d.T.string)]),
  withDefinition(definition): { Properties+: { Definition: definition } },
  '#withDefinitionS3Location':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html#cfn-stepfunctions-statemachine-definitions3location', args=[d.arg(name='definitionS3location', type=d.T.string)]),
  withDefinitionS3Location(definitionS3location): { Properties+: { DefinitionS3Location: definitionS3location } },
  '#withDefinitionString':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html#cfn-stepfunctions-statemachine-definitionstring', args=[d.arg(name='definitionString', type=d.T.string)]),
  withDefinitionString(definitionString): { Properties+: { DefinitionString: definitionString } },
  '#withDefinitionSubstitutions':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html#cfn-stepfunctions-statemachine-definitionsubstitutions', args=[d.arg(name='definitionSubstitutions', type=d.T.string)]),
  withDefinitionSubstitutions(definitionSubstitutions): { Properties+: { DefinitionSubstitutions: definitionSubstitutions } },
  '#withLoggingConfiguration':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html#cfn-stepfunctions-statemachine-loggingconfiguration', args=[d.arg(name='loggingConfiguration', type=d.T.string)]),
  withLoggingConfiguration(loggingConfiguration): { Properties+: { LoggingConfiguration: loggingConfiguration } },
  '#withRoleArn':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html#cfn-stepfunctions-statemachine-rolearn', args=[d.arg(name='roleArn', type=d.T.string)]),
  withRoleArn(roleArn): { Properties+: { RoleArn: roleArn } },
  '#withStateMachineName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html#cfn-stepfunctions-statemachine-statemachinename', args=[d.arg(name='stateMachineName', type=d.T.string)]),
  withStateMachineName(stateMachineName): { Properties+: { StateMachineName: stateMachineName } },
  '#withStateMachineType':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html#cfn-stepfunctions-statemachine-statemachinetype', args=[d.arg(name='stateMachineType', type=d.T.string)]),
  withStateMachineType(stateMachineType): { Properties+: { StateMachineType: stateMachineType } },
  '#withTags':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html#cfn-stepfunctions-statemachine-tags', args=[d.arg(name='tags', type=d.T.string)]),
  withTags(tags): { Properties+: { Tags: tags } },
  '#withTracingConfiguration':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html#cfn-stepfunctions-statemachine-tracingconfiguration', args=[d.arg(name='tracingConfiguration', type=d.T.string)]),
  withTracingConfiguration(tracingConfiguration): { Properties+: { TracingConfiguration: tracingConfiguration } },
}
