(import '../../../extensions/attributes.libsonnet') + {
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='Grant', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-licensemanager-grant.html'),
  new(errorOnEmptyProp=true): { Type: 'AWS::LicenseManager::Grant', Properties: {} },
  '#new':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-licensemanager-grant.html', args=[d.arg(name='errorOnEmptyProp', type=d.T.bool)]),
  '#withAllowedOperations':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-licensemanager-grant.html#cfn-licensemanager-grant-allowedoperations', args=[d.arg(name='allowedOperations', type=d.T.array)]),
  withAllowedOperations(allowedOperations): { Properties+: { AllowedOperations: allowedOperations } },
  '#withAllowedOperationsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-licensemanager-grant.html#cfn-licensemanager-grant-allowedoperations', args=[d.arg(name='allowedOperations', type=d.T.array)]),
  withAllowedOperationsMixin(allowedOperations): { Properties+: { AllowedOperations+: allowedOperations } },
  '#withGrantName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-licensemanager-grant.html#cfn-licensemanager-grant-grantname', args=[d.arg(name='grantName', type=d.T.string)]),
  withGrantName(grantName): { Properties+: { GrantName: grantName } },
  '#withHomeRegion':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-licensemanager-grant.html#cfn-licensemanager-grant-homeregion', args=[d.arg(name='homeRegion', type=d.T.string)]),
  withHomeRegion(homeRegion): { Properties+: { HomeRegion: homeRegion } },
  '#withLicenseArn':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-licensemanager-grant.html#cfn-licensemanager-grant-licensearn', args=[d.arg(name='licenseArn', type=d.T.string)]),
  withLicenseArn(licenseArn): { Properties+: { LicenseArn: licenseArn } },
  '#withPrincipals':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-licensemanager-grant.html#cfn-licensemanager-grant-principals', args=[d.arg(name='principals', type=d.T.array)]),
  withPrincipals(principals): { Properties+: { Principals: principals } },
  '#withPrincipalsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-licensemanager-grant.html#cfn-licensemanager-grant-principals', args=[d.arg(name='principals', type=d.T.array)]),
  withPrincipalsMixin(principals): { Properties+: { Principals+: principals } },
  '#withStatus':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-licensemanager-grant.html#cfn-licensemanager-grant-status', args=[d.arg(name='status', type=d.T.string)]),
  withStatus(status): { Properties+: { Status: status } },
}
