(import '../../../extensions/attributes.libsonnet') + {
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='CertificateAuthority', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-acmpca-certificateauthority.html'),
  new(errorOnEmptyProp=true): { Type: 'AWS::ACMPCA::CertificateAuthority', Properties: { Type: if errorOnEmptyProp then (error 'You need to define Type properties for AWS::ACMPCA::CertificateAuthority resource') else null, KeyAlgorithm: if errorOnEmptyProp then (error 'You need to define KeyAlgorithm properties for AWS::ACMPCA::CertificateAuthority resource') else null, SigningAlgorithm: if errorOnEmptyProp then (error 'You need to define SigningAlgorithm properties for AWS::ACMPCA::CertificateAuthority resource') else null, Subject: if errorOnEmptyProp then (error 'You need to define Subject properties for AWS::ACMPCA::CertificateAuthority resource') else null } },
  '#new':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-acmpca-certificateauthority.html', args=[d.arg(name='errorOnEmptyProp', type=d.T.bool)]),
  '#withCsrExtensions':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-acmpca-certificateauthority.html#cfn-acmpca-certificateauthority-csrextensions', args=[d.arg(name='csrExtensions', type=d.T.object)]),
  withCsrExtensions(csrExtensions): { Properties+: { CsrExtensions: csrExtensions } },
  '#withCsrExtensionsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-acmpca-certificateauthority.html#cfn-acmpca-certificateauthority-csrextensions', args=[d.arg(name='csrExtensions', type=d.T.object)]),
  withCsrExtensionsMixin(csrExtensions): { Properties+: { CsrExtensions+: csrExtensions } },
  '#withKeyAlgorithm':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-acmpca-certificateauthority.html#cfn-acmpca-certificateauthority-keyalgorithm', args=[d.arg(name='keyAlgorithm', type=d.T.string)]),
  withKeyAlgorithm(keyAlgorithm): { Properties+: { KeyAlgorithm: keyAlgorithm } },
  '#withKeyStorageSecurityStandard':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-acmpca-certificateauthority.html#cfn-acmpca-certificateauthority-keystoragesecuritystandard', args=[d.arg(name='keyStorageSecurityStandard', type=d.T.string)]),
  withKeyStorageSecurityStandard(keyStorageSecurityStandard): { Properties+: { KeyStorageSecurityStandard: keyStorageSecurityStandard } },
  '#withRevocationConfiguration':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-acmpca-certificateauthority.html#cfn-acmpca-certificateauthority-revocationconfiguration', args=[d.arg(name='revocationConfiguration', type=d.T.object)]),
  withRevocationConfiguration(revocationConfiguration): { Properties+: { RevocationConfiguration: revocationConfiguration } },
  '#withRevocationConfigurationMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-acmpca-certificateauthority.html#cfn-acmpca-certificateauthority-revocationconfiguration', args=[d.arg(name='revocationConfiguration', type=d.T.object)]),
  withRevocationConfigurationMixin(revocationConfiguration): { Properties+: { RevocationConfiguration+: revocationConfiguration } },
  '#withSigningAlgorithm':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-acmpca-certificateauthority.html#cfn-acmpca-certificateauthority-signingalgorithm', args=[d.arg(name='signingAlgorithm', type=d.T.string)]),
  withSigningAlgorithm(signingAlgorithm): { Properties+: { SigningAlgorithm: signingAlgorithm } },
  '#withSubject':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-acmpca-certificateauthority.html#cfn-acmpca-certificateauthority-subject', args=[d.arg(name='subject', type=d.T.object)]),
  withSubject(subject): { Properties+: { Subject: subject } },
  '#withSubjectMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-acmpca-certificateauthority.html#cfn-acmpca-certificateauthority-subject', args=[d.arg(name='subject', type=d.T.object)]),
  withSubjectMixin(subject): { Properties+: { Subject+: subject } },
  '#withTags':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-acmpca-certificateauthority.html#cfn-acmpca-certificateauthority-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTags(tags): { Properties+: { Tags: tags } },
  '#withTagsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-acmpca-certificateauthority.html#cfn-acmpca-certificateauthority-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTagsMixin(tags): { Properties+: { Tags+: tags } },
  '#withType':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-acmpca-certificateauthority.html#cfn-acmpca-certificateauthority-type', args=[d.arg(name='type', type=d.T.string)]),
  withType(type): { Properties+: { Type: type } },
}
