(import '../../../extensions/attributes.libsonnet') + {
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='PublicRepository', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-publicrepository.html'),
  new(errorOnEmptyProp=true): { Type: 'AWS::ECR::PublicRepository', Properties: {} },
  '#new':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-publicrepository.html', args=[d.arg(name='errorOnEmptyProp', type=d.T.bool)]),
  '#withRepositoryCatalogData':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-publicrepository.html#cfn-ecr-publicrepository-repositorycatalogdata', args=[d.arg(name='repositoryCatalogData', type=d.T.object)]),
  withRepositoryCatalogData(repositoryCatalogData): { Properties+: { RepositoryCatalogData: repositoryCatalogData } },
  '#withRepositoryCatalogDataMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-publicrepository.html#cfn-ecr-publicrepository-repositorycatalogdata', args=[d.arg(name='repositoryCatalogData', type=d.T.object)]),
  withRepositoryCatalogDataMixin(repositoryCatalogData): { Properties+: { RepositoryCatalogData+: repositoryCatalogData } },
  '#withRepositoryName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-publicrepository.html#cfn-ecr-publicrepository-repositoryname', args=[d.arg(name='repositoryName', type=d.T.string)]),
  withRepositoryName(repositoryName): { Properties+: { RepositoryName: repositoryName } },
  '#withRepositoryPolicyText':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-publicrepository.html#cfn-ecr-publicrepository-repositorypolicytext', args=[d.arg(name='repositoryPolicyText', type=d.T.object)]),
  withRepositoryPolicyText(repositoryPolicyText): { Properties+: { RepositoryPolicyText: repositoryPolicyText } },
  '#withRepositoryPolicyTextMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-publicrepository.html#cfn-ecr-publicrepository-repositorypolicytext', args=[d.arg(name='repositoryPolicyText', type=d.T.object)]),
  withRepositoryPolicyTextMixin(repositoryPolicyText): { Properties+: { RepositoryPolicyText+: repositoryPolicyText } },
  '#withTags':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-publicrepository.html#cfn-ecr-publicrepository-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTags(tags): { Properties+: { Tags: tags } },
  '#withTagsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-publicrepository.html#cfn-ecr-publicrepository-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTagsMixin(tags): { Properties+: { Tags+: tags } },
}
