{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='DeploymentStrategy', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appconfig-deploymentstrategy.html'),
  '#withDeploymentDurationInMinutes':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appconfig-deploymentstrategy.html#cfn-appconfig-deploymentstrategy-deploymentdurationinminutes', args=[d.arg(name='deploymentDurationInMinutes', type=d.T.string)]),
  withDeploymentDurationInMinutes(deploymentDurationInMinutes): { Properties+: { DeploymentDurationInMinutes: deploymentDurationInMinutes } },
  '#withDescription':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appconfig-deploymentstrategy.html#cfn-appconfig-deploymentstrategy-description', args=[d.arg(name='description', type=d.T.string)]),
  withDescription(description): { Properties+: { Description: description } },
  '#withFinalBakeTimeInMinutes':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appconfig-deploymentstrategy.html#cfn-appconfig-deploymentstrategy-finalbaketimeinminutes', args=[d.arg(name='finalBakeTimeInMinutes', type=d.T.string)]),
  withFinalBakeTimeInMinutes(finalBakeTimeInMinutes): { Properties+: { FinalBakeTimeInMinutes: finalBakeTimeInMinutes } },
  '#withGrowthFactor':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appconfig-deploymentstrategy.html#cfn-appconfig-deploymentstrategy-growthfactor', args=[d.arg(name='growthFactor', type=d.T.string)]),
  withGrowthFactor(growthFactor): { Properties+: { GrowthFactor: growthFactor } },
  '#withGrowthType':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appconfig-deploymentstrategy.html#cfn-appconfig-deploymentstrategy-growthtype', args=[d.arg(name='growthType', type=d.T.string)]),
  withGrowthType(growthType): { Properties+: { GrowthType: growthType } },
  '#withName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appconfig-deploymentstrategy.html#cfn-appconfig-deploymentstrategy-name', args=[d.arg(name='name', type=d.T.string)]),
  withName(name): { Properties+: { Name: name } },
  '#withReplicateTo':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appconfig-deploymentstrategy.html#cfn-appconfig-deploymentstrategy-replicateto', args=[d.arg(name='replicateTo', type=d.T.string)]),
  withReplicateTo(replicateTo): { Properties+: { ReplicateTo: replicateTo } },
  '#withTags':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appconfig-deploymentstrategy.html#cfn-appconfig-deploymentstrategy-tags', args=[d.arg(name='tags', type=d.T.string)]),
  withTags(tags): { Properties+: { Tags: tags } },
}
