{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='Method', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-method.html'),
  '#withApiKeyRequired':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-method.html#cfn-apigateway-method-apikeyrequired', args=[d.arg(name='apiKeyRequired', type=d.T.string)]),
  withApiKeyRequired(apiKeyRequired): { Properties+: { ApiKeyRequired: apiKeyRequired } },
  '#withAuthorizationScopes':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-method.html#cfn-apigateway-method-authorizationscopes', args=[d.arg(name='authorizationScopes', type=d.T.string)]),
  withAuthorizationScopes(authorizationScopes): { Properties+: { AuthorizationScopes: authorizationScopes } },
  '#withAuthorizationType':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-method.html#cfn-apigateway-method-authorizationtype', args=[d.arg(name='authorizationType', type=d.T.string)]),
  withAuthorizationType(authorizationType): { Properties+: { AuthorizationType: authorizationType } },
  '#withAuthorizerId':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-method.html#cfn-apigateway-method-authorizerid', args=[d.arg(name='authorizerId', type=d.T.string)]),
  withAuthorizerId(authorizerId): { Properties+: { AuthorizerId: authorizerId } },
  '#withHttpMethod':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-method.html#cfn-apigateway-method-httpmethod', args=[d.arg(name='httpMethod', type=d.T.string)]),
  withHttpMethod(httpMethod): { Properties+: { HttpMethod: httpMethod } },
  '#withIntegration':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-method.html#cfn-apigateway-method-integration', args=[d.arg(name='integration', type=d.T.string)]),
  withIntegration(integration): { Properties+: { Integration: integration } },
  '#withMethodResponses':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-method.html#cfn-apigateway-method-methodresponses', args=[d.arg(name='methodResponses', type=d.T.string)]),
  withMethodResponses(methodResponses): { Properties+: { MethodResponses: methodResponses } },
  '#withOperationName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-method.html#cfn-apigateway-method-operationname', args=[d.arg(name='operationName', type=d.T.string)]),
  withOperationName(operationName): { Properties+: { OperationName: operationName } },
  '#withRequestModels':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-method.html#cfn-apigateway-method-requestmodels', args=[d.arg(name='requestModels', type=d.T.string)]),
  withRequestModels(requestModels): { Properties+: { RequestModels: requestModels } },
  '#withRequestParameters':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-method.html#cfn-apigateway-method-requestparameters', args=[d.arg(name='requestParameters', type=d.T.string)]),
  withRequestParameters(requestParameters): { Properties+: { RequestParameters: requestParameters } },
  '#withRequestValidatorId':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-method.html#cfn-apigateway-method-requestvalidatorid', args=[d.arg(name='requestValidatorId', type=d.T.string)]),
  withRequestValidatorId(requestValidatorId): { Properties+: { RequestValidatorId: requestValidatorId } },
  '#withResourceId':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-method.html#cfn-apigateway-method-resourceid', args=[d.arg(name='resourceId', type=d.T.string)]),
  withResourceId(resourceId): { Properties+: { ResourceId: resourceId } },
  '#withRestApiId':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-method.html#cfn-apigateway-method-restapiid', args=[d.arg(name='restApiId', type=d.T.string)]),
  withRestApiId(restApiId): { Properties+: { RestApiId: restApiId } },
}
