{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='AWS.EC2.SecurityGroupIngress', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-ingress.html'),
  '#withCidrIp':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-ingress.html#cfn-ec2-security-group-ingress-cidrip', args=[d.arg(name='cidrIp', type=d.T.string)]),
  withCidrIp(cidrIp): { Properties+: { CidrIp: cidrIp } },
  '#withCidrIpv6':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-ingress.html#cfn-ec2-security-group-ingress-cidripv6', args=[d.arg(name='cidrIpv6', type=d.T.string)]),
  withCidrIpv6(cidrIpv6): { Properties+: { CidrIpv6: cidrIpv6 } },
  '#withDescription':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-ingress.html#cfn-ec2-security-group-ingress-description', args=[d.arg(name='description', type=d.T.string)]),
  withDescription(description): { Properties+: { Description: description } },
  '#withFromPort':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-ingress.html#cfn-ec2-security-group-ingress-fromport', args=[d.arg(name='fromPort', type=d.T.string)]),
  withFromPort(fromPort): { Properties+: { FromPort: fromPort } },
  '#withGroupId':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-ingress.html#cfn-ec2-security-group-ingress-groupid', args=[d.arg(name='groupId', type=d.T.string)]),
  withGroupId(groupId): { Properties+: { GroupId: groupId } },
  '#withGroupName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-ingress.html#cfn-ec2-security-group-ingress-groupname', args=[d.arg(name='groupName', type=d.T.string)]),
  withGroupName(groupName): { Properties+: { GroupName: groupName } },
  '#withIpProtocol':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-ingress.html#cfn-ec2-security-group-ingress-ipprotocol', args=[d.arg(name='ipProtocol', type=d.T.string)]),
  withIpProtocol(ipProtocol): { Properties+: { IpProtocol: ipProtocol } },
  '#withSourcePrefixListId':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-ingress.html#cfn-ec2-securitygroupingress-sourceprefixlistid', args=[d.arg(name='sourcePrefixListId', type=d.T.string)]),
  withSourcePrefixListId(sourcePrefixListId): { Properties+: { SourcePrefixListId: sourcePrefixListId } },
  '#withSourceSecurityGroupId':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-ingress.html#cfn-ec2-security-group-ingress-sourcesecuritygroupid', args=[d.arg(name='sourceSecurityGroupId', type=d.T.string)]),
  withSourceSecurityGroupId(sourceSecurityGroupId): { Properties+: { SourceSecurityGroupId: sourceSecurityGroupId } },
  '#withSourceSecurityGroupName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-ingress.html#cfn-ec2-security-group-ingress-sourcesecuritygroupname', args=[d.arg(name='sourceSecurityGroupName', type=d.T.string)]),
  withSourceSecurityGroupName(sourceSecurityGroupName): { Properties+: { SourceSecurityGroupName: sourceSecurityGroupName } },
  '#withSourceSecurityGroupOwnerId':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-ingress.html#cfn-ec2-security-group-ingress-sourcesecuritygroupownerid', args=[d.arg(name='sourceSecurityGroupOwnerId', type=d.T.string)]),
  withSourceSecurityGroupOwnerId(sourceSecurityGroupOwnerId): { Properties+: { SourceSecurityGroupOwnerId: sourceSecurityGroupOwnerId } },
  '#withToPort':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-ingress.html#cfn-ec2-security-group-ingress-toport', args=[d.arg(name='toPort', type=d.T.string)]),
  withToPort(toPort): { Properties+: { ToPort: toPort } },
}
