{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='ScalingPolicy', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-policy.html'),
  new(): { Type: 'AWS::AutoScaling::ScalingPolicy', Properties: { AutoScalingGroupName: (error 'You need to define AutoScalingGroupName properties for AWS::AutoScaling::ScalingPolicy resource') } },
  '#new':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-policy.html', args=[]),
  dependsOn(dependencies=[]): { DependsOn: dependencies },
  '#dependsOn':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-dependson.html', args=[d.arg(name='dependencies', type=d.T.array)]),
  dependsOnMixin(dependencies=[]): { DependsOn+: dependencies },
  '#dependsOnMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-dependson.html', args=[d.arg(name='dependencies', type=d.T.array)]),
  creationPolicy(policy={}): { CreationPolicy: policy },
  '#creationPolicy':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-creationpolicy.html', args=[d.arg(name='policy', type=d.T.object)]),
  creationPolicyMixin(policy={}): { CreationPolicy+: policy },
  '#creationPolicyMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-creationpolicy.html', args=[d.arg(name='policy', type=d.T.object)]),
  deletionPolicy(policy={}): { DeletionPolicy: policy },
  '#deletionPolicy':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html', args=[d.arg(name='policy', type=d.T.object)]),
  deletionPolicyMixin(policy={}): { DeletionPolicy+: policy },
  '#deletionPolicyMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html', args=[d.arg(name='policy', type=d.T.object)]),
  updatePolicy(policy={}): { UpdatePolicy: policy },
  '#updatePolicy':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatepolicy.html', args=[d.arg(name='policy', type=d.T.object)]),
  updatePolicyMixin(policy={}): { UpdatePolicy+: policy },
  '#updatePolicyMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatepolicy.html', args=[d.arg(name='policy', type=d.T.object)]),
  updateReplacePolicy(policy={}): { UpdateReplacePolicy: policy },
  '#updateReplacePolicy':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatereplacepolicy.html', args=[d.arg(name='policy', type=d.T.object)]),
  updateReplacePolicyMixin(policy={}): { UpdateReplacePolicy+: policy },
  '#updateReplacePolicyMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatereplacepolicy.html', args=[d.arg(name='policy', type=d.T.object)]),
  metadata(metadatas=[]): { Metadata: metadatas },
  '#metadata':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-metadata.html', args=[d.arg(name='metadatas', type=d.T.object)]),
  metadataMixin(metadatas=[]): { Metadata+: metadatas },
  '#metadataMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-metadata.html', args=[d.arg(name='metadatas', type=d.T.object)]),
  '#withAdjustmentType':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-policy.html#cfn-as-scalingpolicy-adjustmenttype', args=[d.arg(name='adjustmentType', type=d.T.string)]),
  withAdjustmentType(adjustmentType): { Properties+: { AdjustmentType: adjustmentType } },
  '#withAutoScalingGroupName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-policy.html#cfn-as-scalingpolicy-autoscalinggroupname', args=[d.arg(name='autoScalingGroupName', type=d.T.string)]),
  withAutoScalingGroupName(autoScalingGroupName): { Properties+: { AutoScalingGroupName: autoScalingGroupName } },
  '#withCooldown':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-policy.html#cfn-as-scalingpolicy-cooldown', args=[d.arg(name='cooldown', type=d.T.string)]),
  withCooldown(cooldown): { Properties+: { Cooldown: cooldown } },
  '#withEstimatedInstanceWarmup':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-policy.html#cfn-as-scalingpolicy-estimatedinstancewarmup', args=[d.arg(name='estimatedInstanceWarmup', type=d.T.number)]),
  withEstimatedInstanceWarmup(estimatedInstanceWarmup): { Properties+: { EstimatedInstanceWarmup: estimatedInstanceWarmup } },
  '#withMetricAggregationType':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-policy.html#cfn-as-scalingpolicy-metricaggregationtype', args=[d.arg(name='metricAggregationType', type=d.T.string)]),
  withMetricAggregationType(metricAggregationType): { Properties+: { MetricAggregationType: metricAggregationType } },
  '#withMinAdjustmentMagnitude':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-policy.html#cfn-as-scalingpolicy-minadjustmentmagnitude', args=[d.arg(name='minAdjustmentMagnitude', type=d.T.number)]),
  withMinAdjustmentMagnitude(minAdjustmentMagnitude): { Properties+: { MinAdjustmentMagnitude: minAdjustmentMagnitude } },
  '#withPolicyType':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-policy.html#cfn-as-scalingpolicy-policytype', args=[d.arg(name='policyType', type=d.T.string)]),
  withPolicyType(policyType): { Properties+: { PolicyType: policyType } },
  '#withPredictiveScalingConfiguration':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-policy.html#cfn-autoscaling-scalingpolicy-predictivescalingconfiguration', args=[d.arg(name='predictiveScalingConfiguration', type=d.T.object)]),
  withPredictiveScalingConfiguration(predictiveScalingConfiguration): { Properties+: { PredictiveScalingConfiguration: predictiveScalingConfiguration } },
  '#withPredictiveScalingConfigurationMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-policy.html#cfn-autoscaling-scalingpolicy-predictivescalingconfiguration', args=[d.arg(name='predictiveScalingConfiguration', type=d.T.object)]),
  withPredictiveScalingConfigurationMixin(predictiveScalingConfiguration): { Properties+: { PredictiveScalingConfiguration+: predictiveScalingConfiguration } },
  '#withScalingAdjustment':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-policy.html#cfn-as-scalingpolicy-scalingadjustment', args=[d.arg(name='scalingAdjustment', type=d.T.number)]),
  withScalingAdjustment(scalingAdjustment): { Properties+: { ScalingAdjustment: scalingAdjustment } },
  '#withStepAdjustments':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-policy.html#cfn-as-scalingpolicy-stepadjustments', args=[d.arg(name='stepAdjustments', type=d.T.array)]),
  withStepAdjustments(stepAdjustments): { Properties+: { StepAdjustments: stepAdjustments } },
  '#withStepAdjustmentsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-policy.html#cfn-as-scalingpolicy-stepadjustments', args=[d.arg(name='stepAdjustments', type=d.T.array)]),
  withStepAdjustmentsMixin(stepAdjustments): { Properties+: { StepAdjustments+: stepAdjustments } },
  '#withTargetTrackingConfiguration':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-policy.html#cfn-autoscaling-scalingpolicy-targettrackingconfiguration', args=[d.arg(name='targetTrackingConfiguration', type=d.T.object)]),
  withTargetTrackingConfiguration(targetTrackingConfiguration): { Properties+: { TargetTrackingConfiguration: targetTrackingConfiguration } },
  '#withTargetTrackingConfigurationMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-policy.html#cfn-autoscaling-scalingpolicy-targettrackingconfiguration', args=[d.arg(name='targetTrackingConfiguration', type=d.T.object)]),
  withTargetTrackingConfigurationMixin(targetTrackingConfiguration): { Properties+: { TargetTrackingConfiguration+: targetTrackingConfiguration } },
}
