{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='Queue', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html'),
  '#creationPolicy':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-creationpolicy.html', args=[d.arg(name='policy', type=d.T.object)]),
  creationPolicy(policy={}): { CreationPolicy: policy },
  '#creationPolicyMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-creationpolicy.html', args=[d.arg(name='policy', type=d.T.object)]),
  creationPolicyMixin(policy={}): { CreationPolicy+: policy },
  '#deletionPolicy':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html', args=[d.arg(name='policy', type=d.T.object)]),
  deletionPolicy(policy={}): { DeletionPolicy: policy },
  '#deletionPolicyMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html', args=[d.arg(name='policy', type=d.T.object)]),
  deletionPolicyMixin(policy={}): { DeletionPolicy+: policy },
  '#dependsOn':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-dependson.html', args=[d.arg(name='dependencies', type=d.T.array)]),
  dependsOn(dependencies=[]): { DependsOn: dependencies },
  '#dependsOnMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-dependson.html', args=[d.arg(name='dependencies', type=d.T.array)]),
  dependsOnMixin(dependencies=[]): { DependsOn+: dependencies },
  '#metadata':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-metadata.html', args=[d.arg(name='metadatas', type=d.T.object)]),
  metadata(metadatas=[]): { Metadata: metadatas },
  '#metadataMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-metadata.html', args=[d.arg(name='metadatas', type=d.T.object)]),
  metadataMixin(metadatas=[]): { Metadata+: metadatas },
  '#new':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html', args=[]),
  new(): { Type: 'AWS::SQS::Queue' },
  '#updatePolicy':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatepolicy.html', args=[d.arg(name='policy', type=d.T.object)]),
  updatePolicy(policy={}): { UpdatePolicy: policy },
  '#updatePolicyMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatepolicy.html', args=[d.arg(name='policy', type=d.T.object)]),
  updatePolicyMixin(policy={}): { UpdatePolicy+: policy },
  '#updateReplacePolicy':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatereplacepolicy.html', args=[d.arg(name='policy', type=d.T.object)]),
  updateReplacePolicy(policy={}): { UpdateReplacePolicy: policy },
  '#updateReplacePolicyMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatereplacepolicy.html', args=[d.arg(name='policy', type=d.T.object)]),
  updateReplacePolicyMixin(policy={}): { UpdateReplacePolicy+: policy },
  '#withContentBasedDeduplication':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html#aws-sqs-queue-contentbaseddeduplication', args=[d.arg(name='contentBasedDeduplication', type=d.T.string)]),
  withContentBasedDeduplication(contentBasedDeduplication): { Properties+: { ContentBasedDeduplication: contentBasedDeduplication } },
  '#withDeduplicationScope':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html#aws-sqs-queue-deduplicationscope', args=[d.arg(name='deduplicationScope', type=d.T.string)]),
  withDeduplicationScope(deduplicationScope): { Properties+: { DeduplicationScope: deduplicationScope } },
  '#withDelaySeconds':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html#aws-sqs-queue-delayseconds', args=[d.arg(name='delaySeconds', type=d.T.string)]),
  withDelaySeconds(delaySeconds): { Properties+: { DelaySeconds: delaySeconds } },
  '#withFifoQueue':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html#aws-sqs-queue-fifoqueue', args=[d.arg(name='fifoQueue', type=d.T.string)]),
  withFifoQueue(fifoQueue): { Properties+: { FifoQueue: fifoQueue } },
  '#withFifoThroughputLimit':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html#aws-sqs-queue-fifothroughputlimit', args=[d.arg(name='fifoThroughputLimit', type=d.T.string)]),
  withFifoThroughputLimit(fifoThroughputLimit): { Properties+: { FifoThroughputLimit: fifoThroughputLimit } },
  '#withKmsDataKeyReusePeriodSeconds':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html#aws-sqs-queue-kmsdatakeyreuseperiodseconds', args=[d.arg(name='kmsDataKeyReusePeriodSeconds', type=d.T.string)]),
  withKmsDataKeyReusePeriodSeconds(kmsDataKeyReusePeriodSeconds): { Properties+: { KmsDataKeyReusePeriodSeconds: kmsDataKeyReusePeriodSeconds } },
  '#withKmsMasterKeyId':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html#aws-sqs-queue-kmsmasterkeyid', args=[d.arg(name='kmsMasterKeyId', type=d.T.string)]),
  withKmsMasterKeyId(kmsMasterKeyId): { Properties+: { KmsMasterKeyId: kmsMasterKeyId } },
  '#withMaximumMessageSize':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html#aws-sqs-queue-maxmesgsize', args=[d.arg(name='maximumMessageSize', type=d.T.string)]),
  withMaximumMessageSize(maximumMessageSize): { Properties+: { MaximumMessageSize: maximumMessageSize } },
  '#withMessageRetentionPeriod':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html#aws-sqs-queue-msgretentionperiod', args=[d.arg(name='messageRetentionPeriod', type=d.T.string)]),
  withMessageRetentionPeriod(messageRetentionPeriod): { Properties+: { MessageRetentionPeriod: messageRetentionPeriod } },
  '#withQueueName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html#aws-sqs-queue-name', args=[d.arg(name='queueName', type=d.T.string)]),
  withQueueName(queueName): { Properties+: { QueueName: queueName } },
  '#withReceiveMessageWaitTimeSeconds':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html#aws-sqs-queue-receivemsgwaittime', args=[d.arg(name='receiveMessageWaitTimeSeconds', type=d.T.string)]),
  withReceiveMessageWaitTimeSeconds(receiveMessageWaitTimeSeconds): { Properties+: { ReceiveMessageWaitTimeSeconds: receiveMessageWaitTimeSeconds } },
  '#withRedriveAllowPolicy':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html#aws-sqs-queue-redriveallowpolicy', args=[d.arg(name='redriveAllowPolicy', type=d.T.string)]),
  withRedriveAllowPolicy(redriveAllowPolicy): { Properties+: { RedriveAllowPolicy: redriveAllowPolicy } },
  '#withRedrivePolicy':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html#aws-sqs-queue-redrive', args=[d.arg(name='redrivePolicy', type=d.T.string)]),
  withRedrivePolicy(redrivePolicy): { Properties+: { RedrivePolicy: redrivePolicy } },
  '#withTags':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html#cfn-sqs-queue-tags', args=[d.arg(name='tags', type=d.T.string)]),
  withTags(tags): { Properties+: { Tags: tags } },
  '#withVisibilityTimeout':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html#aws-sqs-queue-visiblitytimeout', args=[d.arg(name='visibilityTimeout', type=d.T.string)]),
  withVisibilityTimeout(visibilityTimeout): { Properties+: { VisibilityTimeout: visibilityTimeout } },
}
