{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='AWS.SNS.Subscription', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-subscription.html'),
  '#withDeliveryPolicy':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-subscription.html#cfn-sns-subscription-deliverypolicy', args=[d.arg(name='deliveryPolicy', type=d.T.string)]),
  withDeliveryPolicy(deliveryPolicy): { Properties+: { DeliveryPolicy: deliveryPolicy } },
  '#withEndpoint':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-subscription.html#cfn-sns-endpoint', args=[d.arg(name='endpoint', type=d.T.string)]),
  withEndpoint(endpoint): { Properties+: { Endpoint: endpoint } },
  '#withFilterPolicy':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-subscription.html#cfn-sns-subscription-filterpolicy', args=[d.arg(name='filterPolicy', type=d.T.string)]),
  withFilterPolicy(filterPolicy): { Properties+: { FilterPolicy: filterPolicy } },
  '#withProtocol':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-subscription.html#cfn-sns-protocol', args=[d.arg(name='protocol', type=d.T.string)]),
  withProtocol(protocol): { Properties+: { Protocol: protocol } },
  '#withRawMessageDelivery':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-subscription.html#cfn-sns-subscription-rawmessagedelivery', args=[d.arg(name='rawMessageDelivery', type=d.T.string)]),
  withRawMessageDelivery(rawMessageDelivery): { Properties+: { RawMessageDelivery: rawMessageDelivery } },
  '#withRedrivePolicy':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-subscription.html#cfn-sns-subscription-redrivepolicy', args=[d.arg(name='redrivePolicy', type=d.T.string)]),
  withRedrivePolicy(redrivePolicy): { Properties+: { RedrivePolicy: redrivePolicy } },
  '#withRegion':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-subscription.html#cfn-sns-subscription-region', args=[d.arg(name='region', type=d.T.string)]),
  withRegion(region): { Properties+: { Region: region } },
  '#withSubscriptionRoleArn':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-subscription.html#cfn-sns-subscription-subscriptionrolearn', args=[d.arg(name='subscriptionRoleArn', type=d.T.string)]),
  withSubscriptionRoleArn(subscriptionRoleArn): { Properties+: { SubscriptionRoleArn: subscriptionRoleArn } },
  '#withTopicArn':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-subscription.html#topicarn', args=[d.arg(name='topicArn', type=d.T.string)]),
  withTopicArn(topicArn): { Properties+: { TopicArn: topicArn } },
}
