(import '../../../extensions/attributes.libsonnet') + {
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='ScheduledAudit', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iot-scheduledaudit.html'),
  new(errorOnEmptyProp=true): { Type: 'AWS::IoT::ScheduledAudit', Properties: { TargetCheckNames: if errorOnEmptyProp then (error 'You need to define TargetCheckNames properties for AWS::IoT::ScheduledAudit resource') else null, Frequency: if errorOnEmptyProp then (error 'You need to define Frequency properties for AWS::IoT::ScheduledAudit resource') else null } },
  '#new':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iot-scheduledaudit.html', args=[d.arg(name='errorOnEmptyProp', type=d.T.bool)]),
  '#withDayOfMonth':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iot-scheduledaudit.html#cfn-iot-scheduledaudit-dayofmonth', args=[d.arg(name='dayOfMonth', type=d.T.string)]),
  withDayOfMonth(dayOfMonth): { Properties+: { DayOfMonth: dayOfMonth } },
  '#withDayOfWeek':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iot-scheduledaudit.html#cfn-iot-scheduledaudit-dayofweek', args=[d.arg(name='dayOfWeek', type=d.T.string)]),
  withDayOfWeek(dayOfWeek): { Properties+: { DayOfWeek: dayOfWeek } },
  '#withFrequency':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iot-scheduledaudit.html#cfn-iot-scheduledaudit-frequency', args=[d.arg(name='frequency', type=d.T.string)]),
  withFrequency(frequency): { Properties+: { Frequency: frequency } },
  '#withScheduledAuditName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iot-scheduledaudit.html#cfn-iot-scheduledaudit-scheduledauditname', args=[d.arg(name='scheduledAuditName', type=d.T.string)]),
  withScheduledAuditName(scheduledAuditName): { Properties+: { ScheduledAuditName: scheduledAuditName } },
  '#withTags':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iot-scheduledaudit.html#cfn-iot-scheduledaudit-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTags(tags): { Properties+: { Tags: tags } },
  '#withTagsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iot-scheduledaudit.html#cfn-iot-scheduledaudit-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTagsMixin(tags): { Properties+: { Tags+: tags } },
  '#withTargetCheckNames':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iot-scheduledaudit.html#cfn-iot-scheduledaudit-targetchecknames', args=[d.arg(name='targetCheckNames', type=d.T.array)]),
  withTargetCheckNames(targetCheckNames): { Properties+: { TargetCheckNames: targetCheckNames } },
  '#withTargetCheckNamesMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iot-scheduledaudit.html#cfn-iot-scheduledaudit-targetchecknames', args=[d.arg(name='targetCheckNames', type=d.T.array)]),
  withTargetCheckNamesMixin(targetCheckNames): { Properties+: { TargetCheckNames+: targetCheckNames } },
}
