(import '../../../extensions/attributes.libsonnet') + {
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='Service', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apprunner-service.html'),
  new(errorOnEmptyProp=true): { Type: 'AWS::AppRunner::Service', Properties: { SourceConfiguration: if errorOnEmptyProp then (error 'You need to define SourceConfiguration properties for AWS::AppRunner::Service resource') else null } },
  '#new':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apprunner-service.html', args=[d.arg(name='errorOnEmptyProp', type=d.T.bool)]),
  '#withAutoScalingConfigurationArn':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apprunner-service.html#cfn-apprunner-service-autoscalingconfigurationarn', args=[d.arg(name='autoScalingConfigurationArn', type=d.T.string)]),
  withAutoScalingConfigurationArn(autoScalingConfigurationArn): { Properties+: { AutoScalingConfigurationArn: autoScalingConfigurationArn } },
  '#withEncryptionConfiguration':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apprunner-service.html#cfn-apprunner-service-encryptionconfiguration', args=[d.arg(name='encryptionConfiguration', type=d.T.object)]),
  withEncryptionConfiguration(encryptionConfiguration): { Properties+: { EncryptionConfiguration: encryptionConfiguration } },
  '#withEncryptionConfigurationMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apprunner-service.html#cfn-apprunner-service-encryptionconfiguration', args=[d.arg(name='encryptionConfiguration', type=d.T.object)]),
  withEncryptionConfigurationMixin(encryptionConfiguration): { Properties+: { EncryptionConfiguration+: encryptionConfiguration } },
  '#withHealthCheckConfiguration':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apprunner-service.html#cfn-apprunner-service-healthcheckconfiguration', args=[d.arg(name='healthCheckConfiguration', type=d.T.object)]),
  withHealthCheckConfiguration(healthCheckConfiguration): { Properties+: { HealthCheckConfiguration: healthCheckConfiguration } },
  '#withHealthCheckConfigurationMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apprunner-service.html#cfn-apprunner-service-healthcheckconfiguration', args=[d.arg(name='healthCheckConfiguration', type=d.T.object)]),
  withHealthCheckConfigurationMixin(healthCheckConfiguration): { Properties+: { HealthCheckConfiguration+: healthCheckConfiguration } },
  '#withInstanceConfiguration':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apprunner-service.html#cfn-apprunner-service-instanceconfiguration', args=[d.arg(name='instanceConfiguration', type=d.T.object)]),
  withInstanceConfiguration(instanceConfiguration): { Properties+: { InstanceConfiguration: instanceConfiguration } },
  '#withInstanceConfigurationMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apprunner-service.html#cfn-apprunner-service-instanceconfiguration', args=[d.arg(name='instanceConfiguration', type=d.T.object)]),
  withInstanceConfigurationMixin(instanceConfiguration): { Properties+: { InstanceConfiguration+: instanceConfiguration } },
  '#withServiceName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apprunner-service.html#cfn-apprunner-service-servicename', args=[d.arg(name='serviceName', type=d.T.string)]),
  withServiceName(serviceName): { Properties+: { ServiceName: serviceName } },
  '#withSourceConfiguration':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apprunner-service.html#cfn-apprunner-service-sourceconfiguration', args=[d.arg(name='sourceConfiguration', type=d.T.object)]),
  withSourceConfiguration(sourceConfiguration): { Properties+: { SourceConfiguration: sourceConfiguration } },
  '#withSourceConfigurationMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apprunner-service.html#cfn-apprunner-service-sourceconfiguration', args=[d.arg(name='sourceConfiguration', type=d.T.object)]),
  withSourceConfigurationMixin(sourceConfiguration): { Properties+: { SourceConfiguration+: sourceConfiguration } },
  '#withTags':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apprunner-service.html#cfn-apprunner-service-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTags(tags): { Properties+: { Tags: tags } },
  '#withTagsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apprunner-service.html#cfn-apprunner-service-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTagsMixin(tags): { Properties+: { Tags+: tags } },
}
