{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='Service', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apprunner-service.html'),
  '#withAutoScalingConfigurationArn':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apprunner-service.html#cfn-apprunner-service-autoscalingconfigurationarn', args=[d.arg(name='autoScalingConfigurationArn', type=d.T.string)]),
  withAutoScalingConfigurationArn(autoScalingConfigurationArn): { Properties+: { AutoScalingConfigurationArn: autoScalingConfigurationArn } },
  '#withEncryptionConfiguration':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apprunner-service.html#cfn-apprunner-service-encryptionconfiguration', args=[d.arg(name='encryptionConfiguration', type=d.T.string)]),
  withEncryptionConfiguration(encryptionConfiguration): { Properties+: { EncryptionConfiguration: encryptionConfiguration } },
  '#withHealthCheckConfiguration':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apprunner-service.html#cfn-apprunner-service-healthcheckconfiguration', args=[d.arg(name='healthCheckConfiguration', type=d.T.string)]),
  withHealthCheckConfiguration(healthCheckConfiguration): { Properties+: { HealthCheckConfiguration: healthCheckConfiguration } },
  '#withInstanceConfiguration':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apprunner-service.html#cfn-apprunner-service-instanceconfiguration', args=[d.arg(name='instanceConfiguration', type=d.T.string)]),
  withInstanceConfiguration(instanceConfiguration): { Properties+: { InstanceConfiguration: instanceConfiguration } },
  '#withServiceName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apprunner-service.html#cfn-apprunner-service-servicename', args=[d.arg(name='serviceName', type=d.T.string)]),
  withServiceName(serviceName): { Properties+: { ServiceName: serviceName } },
  '#withSourceConfiguration':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apprunner-service.html#cfn-apprunner-service-sourceconfiguration', args=[d.arg(name='sourceConfiguration', type=d.T.string)]),
  withSourceConfiguration(sourceConfiguration): { Properties+: { SourceConfiguration: sourceConfiguration } },
  '#withTags':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apprunner-service.html#cfn-apprunner-service-tags', args=[d.arg(name='tags', type=d.T.string)]),
  withTags(tags): { Properties+: { Tags: tags } },
}
