(import '../../../extensions/attributes.libsonnet') + {
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='Dashboard', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-quicksight-dashboard.html'),
  new(errorOnEmptyProp=true): { Type: 'AWS::QuickSight::Dashboard', Properties: { DashboardId: if errorOnEmptyProp then (error 'You need to define DashboardId properties for AWS::QuickSight::Dashboard resource') else null, AwsAccountId: if errorOnEmptyProp then (error 'You need to define AwsAccountId properties for AWS::QuickSight::Dashboard resource') else null, SourceEntity: if errorOnEmptyProp then (error 'You need to define SourceEntity properties for AWS::QuickSight::Dashboard resource') else null } },
  '#new':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-quicksight-dashboard.html', args=[d.arg(name='errorOnEmptyProp', type=d.T.bool)]),
  '#withAwsAccountId':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-quicksight-dashboard.html#cfn-quicksight-dashboard-awsaccountid', args=[d.arg(name='awsAccountId', type=d.T.string)]),
  withAwsAccountId(awsAccountId): { Properties+: { AwsAccountId: awsAccountId } },
  '#withDashboardId':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-quicksight-dashboard.html#cfn-quicksight-dashboard-dashboardid', args=[d.arg(name='dashboardId', type=d.T.string)]),
  withDashboardId(dashboardId): { Properties+: { DashboardId: dashboardId } },
  '#withDashboardPublishOptions':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-quicksight-dashboard.html#cfn-quicksight-dashboard-dashboardpublishoptions', args=[d.arg(name='dashboardPublishOptions', type=d.T.object)]),
  withDashboardPublishOptions(dashboardPublishOptions): { Properties+: { DashboardPublishOptions: dashboardPublishOptions } },
  '#withDashboardPublishOptionsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-quicksight-dashboard.html#cfn-quicksight-dashboard-dashboardpublishoptions', args=[d.arg(name='dashboardPublishOptions', type=d.T.object)]),
  withDashboardPublishOptionsMixin(dashboardPublishOptions): { Properties+: { DashboardPublishOptions+: dashboardPublishOptions } },
  '#withName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-quicksight-dashboard.html#cfn-quicksight-dashboard-name', args=[d.arg(name='name', type=d.T.string)]),
  withName(name): { Properties+: { Name: name } },
  '#withParameters':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-quicksight-dashboard.html#cfn-quicksight-dashboard-parameters', args=[d.arg(name='parameters', type=d.T.object)]),
  withParameters(parameters): { Properties+: { Parameters: parameters } },
  '#withParametersMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-quicksight-dashboard.html#cfn-quicksight-dashboard-parameters', args=[d.arg(name='parameters', type=d.T.object)]),
  withParametersMixin(parameters): { Properties+: { Parameters+: parameters } },
  '#withPermissions':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-quicksight-dashboard.html#cfn-quicksight-dashboard-permissions', args=[d.arg(name='permissions', type=d.T.array)]),
  withPermissions(permissions): { Properties+: { Permissions: permissions } },
  '#withPermissionsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-quicksight-dashboard.html#cfn-quicksight-dashboard-permissions', args=[d.arg(name='permissions', type=d.T.array)]),
  withPermissionsMixin(permissions): { Properties+: { Permissions+: permissions } },
  '#withSourceEntity':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-quicksight-dashboard.html#cfn-quicksight-dashboard-sourceentity', args=[d.arg(name='sourceEntity', type=d.T.object)]),
  withSourceEntity(sourceEntity): { Properties+: { SourceEntity: sourceEntity } },
  '#withSourceEntityMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-quicksight-dashboard.html#cfn-quicksight-dashboard-sourceentity', args=[d.arg(name='sourceEntity', type=d.T.object)]),
  withSourceEntityMixin(sourceEntity): { Properties+: { SourceEntity+: sourceEntity } },
  '#withTags':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-quicksight-dashboard.html#cfn-quicksight-dashboard-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTags(tags): { Properties+: { Tags: tags } },
  '#withTagsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-quicksight-dashboard.html#cfn-quicksight-dashboard-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTagsMixin(tags): { Properties+: { Tags+: tags } },
  '#withThemeArn':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-quicksight-dashboard.html#cfn-quicksight-dashboard-themearn', args=[d.arg(name='themeArn', type=d.T.string)]),
  withThemeArn(themeArn): { Properties+: { ThemeArn: themeArn } },
  '#withVersionDescription':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-quicksight-dashboard.html#cfn-quicksight-dashboard-versiondescription', args=[d.arg(name='versionDescription', type=d.T.string)]),
  withVersionDescription(versionDescription): { Properties+: { VersionDescription: versionDescription } },
}
