{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='Canary', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-synthetics-canary.html'),
  '#withArtifactConfig':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-synthetics-canary.html#cfn-synthetics-canary-artifactconfig', args=[d.arg(name='artifactConfig', type=d.T.string)]),
  withArtifactConfig(artifactConfig): { Properties+: { ArtifactConfig: artifactConfig } },
  '#withArtifactS3Location':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-synthetics-canary.html#cfn-synthetics-canary-artifacts3location', args=[d.arg(name='artifactS3location', type=d.T.string)]),
  withArtifactS3Location(artifactS3location): { Properties+: { ArtifactS3Location: artifactS3location } },
  '#withCode':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-synthetics-canary.html#cfn-synthetics-canary-code', args=[d.arg(name='code', type=d.T.string)]),
  withCode(code): { Properties+: { Code: code } },
  '#withExecutionRoleArn':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-synthetics-canary.html#cfn-synthetics-canary-executionrolearn', args=[d.arg(name='executionRoleArn', type=d.T.string)]),
  withExecutionRoleArn(executionRoleArn): { Properties+: { ExecutionRoleArn: executionRoleArn } },
  '#withFailureRetentionPeriod':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-synthetics-canary.html#cfn-synthetics-canary-failureretentionperiod', args=[d.arg(name='failureRetentionPeriod', type=d.T.string)]),
  withFailureRetentionPeriod(failureRetentionPeriod): { Properties+: { FailureRetentionPeriod: failureRetentionPeriod } },
  '#withName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-synthetics-canary.html#cfn-synthetics-canary-name', args=[d.arg(name='name', type=d.T.string)]),
  withName(name): { Properties+: { Name: name } },
  '#withRunConfig':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-synthetics-canary.html#cfn-synthetics-canary-runconfig', args=[d.arg(name='runConfig', type=d.T.string)]),
  withRunConfig(runConfig): { Properties+: { RunConfig: runConfig } },
  '#withRuntimeVersion':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-synthetics-canary.html#cfn-synthetics-canary-runtimeversion', args=[d.arg(name='runtimeVersion', type=d.T.string)]),
  withRuntimeVersion(runtimeVersion): { Properties+: { RuntimeVersion: runtimeVersion } },
  '#withSchedule':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-synthetics-canary.html#cfn-synthetics-canary-schedule', args=[d.arg(name='schedule', type=d.T.string)]),
  withSchedule(schedule): { Properties+: { Schedule: schedule } },
  '#withStartCanaryAfterCreation':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-synthetics-canary.html#cfn-synthetics-canary-startcanaryaftercreation', args=[d.arg(name='startCanaryAfterCreation', type=d.T.string)]),
  withStartCanaryAfterCreation(startCanaryAfterCreation): { Properties+: { StartCanaryAfterCreation: startCanaryAfterCreation } },
  '#withSuccessRetentionPeriod':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-synthetics-canary.html#cfn-synthetics-canary-successretentionperiod', args=[d.arg(name='successRetentionPeriod', type=d.T.string)]),
  withSuccessRetentionPeriod(successRetentionPeriod): { Properties+: { SuccessRetentionPeriod: successRetentionPeriod } },
  '#withTags':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-synthetics-canary.html#cfn-synthetics-canary-tags', args=[d.arg(name='tags', type=d.T.string)]),
  withTags(tags): { Properties+: { Tags: tags } },
  '#withVPCConfig':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-synthetics-canary.html#cfn-synthetics-canary-vpcconfig', args=[d.arg(name='vpcconfig', type=d.T.string)]),
  withVPCConfig(vpcconfig): { Properties+: { VPCConfig: vpcconfig } },
  '#withVisualReference':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-synthetics-canary.html#cfn-synthetics-canary-visualreference', args=[d.arg(name='visualReference', type=d.T.string)]),
  withVisualReference(visualReference): { Properties+: { VisualReference: visualReference } },
}
