(import '../../../extensions/attributes.libsonnet') + {
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='Stack', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stack.html'),
  new(errorOnEmptyProp=true): { Type: 'AWS::CloudFormation::Stack', Properties: { TemplateURL: if errorOnEmptyProp then (error 'You need to define TemplateURL properties for AWS::CloudFormation::Stack resource') else null } },
  '#new':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stack.html', args=[d.arg(name='errorOnEmptyProp', type=d.T.bool)]),
  '#withNotificationARNs':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stack.html#cfn-cloudformation-stack-notificationarns', args=[d.arg(name='notificationArns', type=d.T.array)]),
  withNotificationARNs(notificationArns): { Properties+: { NotificationARNs: notificationArns } },
  '#withNotificationARNsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stack.html#cfn-cloudformation-stack-notificationarns', args=[d.arg(name='notificationArns', type=d.T.array)]),
  withNotificationARNsMixin(notificationArns): { Properties+: { NotificationARNs+: notificationArns } },
  '#withParameters':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stack.html#cfn-cloudformation-stack-parameters', args=[d.arg(name='parameters', type=d.T.object)]),
  withParameters(parameters): { Properties+: { Parameters: parameters } },
  '#withParametersMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stack.html#cfn-cloudformation-stack-parameters', args=[d.arg(name='parameters', type=d.T.object)]),
  withParametersMixin(parameters): { Properties+: { Parameters+: parameters } },
  '#withTags':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stack.html#cfn-cloudformation-stack-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTags(tags): { Properties+: { Tags: tags } },
  '#withTagsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stack.html#cfn-cloudformation-stack-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTagsMixin(tags): { Properties+: { Tags+: tags } },
  '#withTemplateURL':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stack.html#cfn-cloudformation-stack-templateurl', args=[d.arg(name='templateUrl', type=d.T.string)]),
  withTemplateURL(templateUrl): { Properties+: { TemplateURL: templateUrl } },
  '#withTimeoutInMinutes':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stack.html#cfn-cloudformation-stack-timeoutinminutes', args=[d.arg(name='timeoutInMinutes', type=d.T.number)]),
  withTimeoutInMinutes(timeoutInMinutes): { Properties+: { TimeoutInMinutes: timeoutInMinutes } },
}
