{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='JobDefinition', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-batch-jobdefinition.html'),
  '#withContainerProperties':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-batch-jobdefinition.html#cfn-batch-jobdefinition-containerproperties', args=[d.arg(name='containerProperties', type=d.T.string)]),
  withContainerProperties(containerProperties): { Properties+: { ContainerProperties: containerProperties } },
  '#withJobDefinitionName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-batch-jobdefinition.html#cfn-batch-jobdefinition-jobdefinitionname', args=[d.arg(name='jobDefinitionName', type=d.T.string)]),
  withJobDefinitionName(jobDefinitionName): { Properties+: { JobDefinitionName: jobDefinitionName } },
  '#withNodeProperties':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-batch-jobdefinition.html#cfn-batch-jobdefinition-nodeproperties', args=[d.arg(name='nodeProperties', type=d.T.string)]),
  withNodeProperties(nodeProperties): { Properties+: { NodeProperties: nodeProperties } },
  '#withParameters':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-batch-jobdefinition.html#cfn-batch-jobdefinition-parameters', args=[d.arg(name='parameters', type=d.T.string)]),
  withParameters(parameters): { Properties+: { Parameters: parameters } },
  '#withPlatformCapabilities':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-batch-jobdefinition.html#cfn-batch-jobdefinition-platformcapabilities', args=[d.arg(name='platformCapabilities', type=d.T.string)]),
  withPlatformCapabilities(platformCapabilities): { Properties+: { PlatformCapabilities: platformCapabilities } },
  '#withPropagateTags':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-batch-jobdefinition.html#cfn-batch-jobdefinition-propagatetags', args=[d.arg(name='propagateTags', type=d.T.string)]),
  withPropagateTags(propagateTags): { Properties+: { PropagateTags: propagateTags } },
  '#withRetryStrategy':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-batch-jobdefinition.html#cfn-batch-jobdefinition-retrystrategy', args=[d.arg(name='retryStrategy', type=d.T.string)]),
  withRetryStrategy(retryStrategy): { Properties+: { RetryStrategy: retryStrategy } },
  '#withSchedulingPriority':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-batch-jobdefinition.html#cfn-batch-jobdefinition-schedulingpriority', args=[d.arg(name='schedulingPriority', type=d.T.string)]),
  withSchedulingPriority(schedulingPriority): { Properties+: { SchedulingPriority: schedulingPriority } },
  '#withTags':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-batch-jobdefinition.html#cfn-batch-jobdefinition-tags', args=[d.arg(name='tags', type=d.T.string)]),
  withTags(tags): { Properties+: { Tags: tags } },
  '#withTimeout':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-batch-jobdefinition.html#cfn-batch-jobdefinition-timeout', args=[d.arg(name='timeout', type=d.T.string)]),
  withTimeout(timeout): { Properties+: { Timeout: timeout } },
  '#withType':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-batch-jobdefinition.html#cfn-batch-jobdefinition-type', args=[d.arg(name='type', type=d.T.string)]),
  withType(type): { Properties+: { Type: type } },
}
