(import '../../../extensions/attributes.libsonnet') + {
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='InstanceFleetConfig', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticmapreduce-instancefleetconfig.html'),
  new(errorOnEmptyProp=true): { Type: 'AWS::EMR::InstanceFleetConfig', Properties: { InstanceFleetType: if errorOnEmptyProp then (error 'You need to define InstanceFleetType properties for AWS::EMR::InstanceFleetConfig resource') else null, ClusterId: if errorOnEmptyProp then (error 'You need to define ClusterId properties for AWS::EMR::InstanceFleetConfig resource') else null } },
  '#new':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticmapreduce-instancefleetconfig.html', args=[d.arg(name='errorOnEmptyProp', type=d.T.bool)]),
  '#withClusterId':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticmapreduce-instancefleetconfig.html#cfn-elasticmapreduce-instancefleetconfig-clusterid', args=[d.arg(name='clusterId', type=d.T.string)]),
  withClusterId(clusterId): { Properties+: { ClusterId: clusterId } },
  '#withInstanceFleetType':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticmapreduce-instancefleetconfig.html#cfn-elasticmapreduce-instancefleetconfig-instancefleettype', args=[d.arg(name='instanceFleetType', type=d.T.string)]),
  withInstanceFleetType(instanceFleetType): { Properties+: { InstanceFleetType: instanceFleetType } },
  '#withInstanceTypeConfigs':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticmapreduce-instancefleetconfig.html#cfn-elasticmapreduce-instancefleetconfig-instancetypeconfigs', args=[d.arg(name='instanceTypeConfigs', type=d.T.array)]),
  withInstanceTypeConfigs(instanceTypeConfigs): { Properties+: { InstanceTypeConfigs: instanceTypeConfigs } },
  '#withInstanceTypeConfigsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticmapreduce-instancefleetconfig.html#cfn-elasticmapreduce-instancefleetconfig-instancetypeconfigs', args=[d.arg(name='instanceTypeConfigs', type=d.T.array)]),
  withInstanceTypeConfigsMixin(instanceTypeConfigs): { Properties+: { InstanceTypeConfigs+: instanceTypeConfigs } },
  '#withLaunchSpecifications':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticmapreduce-instancefleetconfig.html#cfn-elasticmapreduce-instancefleetconfig-launchspecifications', args=[d.arg(name='launchSpecifications', type=d.T.object)]),
  withLaunchSpecifications(launchSpecifications): { Properties+: { LaunchSpecifications: launchSpecifications } },
  '#withLaunchSpecificationsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticmapreduce-instancefleetconfig.html#cfn-elasticmapreduce-instancefleetconfig-launchspecifications', args=[d.arg(name='launchSpecifications', type=d.T.object)]),
  withLaunchSpecificationsMixin(launchSpecifications): { Properties+: { LaunchSpecifications+: launchSpecifications } },
  '#withName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticmapreduce-instancefleetconfig.html#cfn-elasticmapreduce-instancefleetconfig-name', args=[d.arg(name='name', type=d.T.string)]),
  withName(name): { Properties+: { Name: name } },
  '#withTargetOnDemandCapacity':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticmapreduce-instancefleetconfig.html#cfn-elasticmapreduce-instancefleetconfig-targetondemandcapacity', args=[d.arg(name='targetOnDemandCapacity', type=d.T.number)]),
  withTargetOnDemandCapacity(targetOnDemandCapacity): { Properties+: { TargetOnDemandCapacity: targetOnDemandCapacity } },
  '#withTargetSpotCapacity':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticmapreduce-instancefleetconfig.html#cfn-elasticmapreduce-instancefleetconfig-targetspotcapacity', args=[d.arg(name='targetSpotCapacity', type=d.T.number)]),
  withTargetSpotCapacity(targetSpotCapacity): { Properties+: { TargetSpotCapacity: targetSpotCapacity } },
}
