(import '../../../extensions/attributes.libsonnet') + {
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='Instance', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html'),
  new(errorOnEmptyProp=true): { Type: 'AWS::EC2::Instance', Properties: {} },
  '#new':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html', args=[d.arg(name='errorOnEmptyProp', type=d.T.bool)]),
  '#withAdditionalInfo':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-additionalinfo', args=[d.arg(name='additionalInfo', type=d.T.string)]),
  withAdditionalInfo(additionalInfo): { Properties+: { AdditionalInfo: additionalInfo } },
  '#withAffinity':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-affinity', args=[d.arg(name='affinity', type=d.T.string)]),
  withAffinity(affinity): { Properties+: { Affinity: affinity } },
  '#withAvailabilityZone':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-availabilityzone', args=[d.arg(name='availabilityZone', type=d.T.string)]),
  withAvailabilityZone(availabilityZone): { Properties+: { AvailabilityZone: availabilityZone } },
  '#withBlockDeviceMappings':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-blockdevicemappings', args=[d.arg(name='blockDeviceMappings', type=d.T.array)]),
  withBlockDeviceMappings(blockDeviceMappings): { Properties+: { BlockDeviceMappings: blockDeviceMappings } },
  '#withBlockDeviceMappingsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-blockdevicemappings', args=[d.arg(name='blockDeviceMappings', type=d.T.array)]),
  withBlockDeviceMappingsMixin(blockDeviceMappings): { Properties+: { BlockDeviceMappings+: blockDeviceMappings } },
  '#withCpuOptions':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-cpuoptions', args=[d.arg(name='cpuOptions', type=d.T.object)]),
  withCpuOptions(cpuOptions): { Properties+: { CpuOptions: cpuOptions } },
  '#withCpuOptionsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-cpuoptions', args=[d.arg(name='cpuOptions', type=d.T.object)]),
  withCpuOptionsMixin(cpuOptions): { Properties+: { CpuOptions+: cpuOptions } },
  '#withCreditSpecification':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-creditspecification', args=[d.arg(name='creditSpecification', type=d.T.object)]),
  withCreditSpecification(creditSpecification): { Properties+: { CreditSpecification: creditSpecification } },
  '#withCreditSpecificationMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-creditspecification', args=[d.arg(name='creditSpecification', type=d.T.object)]),
  withCreditSpecificationMixin(creditSpecification): { Properties+: { CreditSpecification+: creditSpecification } },
  '#withDisableApiTermination':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-disableapitermination', args=[d.arg(name='disableApiTermination', type=d.T.bool)]),
  withDisableApiTermination(disableApiTermination): { Properties+: { DisableApiTermination: disableApiTermination } },
  '#withEbsOptimized':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-ebsoptimized', args=[d.arg(name='ebsOptimized', type=d.T.bool)]),
  withEbsOptimized(ebsOptimized): { Properties+: { EbsOptimized: ebsOptimized } },
  '#withElasticGpuSpecifications':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-elasticgpuspecifications', args=[d.arg(name='elasticGpuSpecifications', type=d.T.array)]),
  withElasticGpuSpecifications(elasticGpuSpecifications): { Properties+: { ElasticGpuSpecifications: elasticGpuSpecifications } },
  '#withElasticGpuSpecificationsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-elasticgpuspecifications', args=[d.arg(name='elasticGpuSpecifications', type=d.T.array)]),
  withElasticGpuSpecificationsMixin(elasticGpuSpecifications): { Properties+: { ElasticGpuSpecifications+: elasticGpuSpecifications } },
  '#withElasticInferenceAccelerators':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-elasticinferenceaccelerators', args=[d.arg(name='elasticInferenceAccelerators', type=d.T.array)]),
  withElasticInferenceAccelerators(elasticInferenceAccelerators): { Properties+: { ElasticInferenceAccelerators: elasticInferenceAccelerators } },
  '#withElasticInferenceAcceleratorsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-elasticinferenceaccelerators', args=[d.arg(name='elasticInferenceAccelerators', type=d.T.array)]),
  withElasticInferenceAcceleratorsMixin(elasticInferenceAccelerators): { Properties+: { ElasticInferenceAccelerators+: elasticInferenceAccelerators } },
  '#withEnclaveOptions':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-enclaveoptions', args=[d.arg(name='enclaveOptions', type=d.T.object)]),
  withEnclaveOptions(enclaveOptions): { Properties+: { EnclaveOptions: enclaveOptions } },
  '#withEnclaveOptionsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-enclaveoptions', args=[d.arg(name='enclaveOptions', type=d.T.object)]),
  withEnclaveOptionsMixin(enclaveOptions): { Properties+: { EnclaveOptions+: enclaveOptions } },
  '#withHibernationOptions':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-hibernationoptions', args=[d.arg(name='hibernationOptions', type=d.T.object)]),
  withHibernationOptions(hibernationOptions): { Properties+: { HibernationOptions: hibernationOptions } },
  '#withHibernationOptionsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-hibernationoptions', args=[d.arg(name='hibernationOptions', type=d.T.object)]),
  withHibernationOptionsMixin(hibernationOptions): { Properties+: { HibernationOptions+: hibernationOptions } },
  '#withHostId':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-hostid', args=[d.arg(name='hostId', type=d.T.string)]),
  withHostId(hostId): { Properties+: { HostId: hostId } },
  '#withHostResourceGroupArn':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-hostresourcegrouparn', args=[d.arg(name='hostResourceGroupArn', type=d.T.string)]),
  withHostResourceGroupArn(hostResourceGroupArn): { Properties+: { HostResourceGroupArn: hostResourceGroupArn } },
  '#withIamInstanceProfile':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-iaminstanceprofile', args=[d.arg(name='iamInstanceProfile', type=d.T.string)]),
  withIamInstanceProfile(iamInstanceProfile): { Properties+: { IamInstanceProfile: iamInstanceProfile } },
  '#withImageId':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-imageid', args=[d.arg(name='imageId', type=d.T.string)]),
  withImageId(imageId): { Properties+: { ImageId: imageId } },
  '#withInstanceInitiatedShutdownBehavior':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-instanceinitiatedshutdownbehavior', args=[d.arg(name='instanceInitiatedShutdownBehavior', type=d.T.string)]),
  withInstanceInitiatedShutdownBehavior(instanceInitiatedShutdownBehavior): { Properties+: { InstanceInitiatedShutdownBehavior: instanceInitiatedShutdownBehavior } },
  '#withInstanceType':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-instancetype', args=[d.arg(name='instanceType', type=d.T.string)]),
  withInstanceType(instanceType): { Properties+: { InstanceType: instanceType } },
  '#withIpv6AddressCount':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-ipv6addresscount', args=[d.arg(name='ipv6addressCount', type=d.T.number)]),
  withIpv6AddressCount(ipv6addressCount): { Properties+: { Ipv6AddressCount: ipv6addressCount } },
  '#withIpv6Addresses':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-ipv6addresses', args=[d.arg(name='ipv6addresses', type=d.T.array)]),
  withIpv6Addresses(ipv6addresses): { Properties+: { Ipv6Addresses: ipv6addresses } },
  '#withIpv6AddressesMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-ipv6addresses', args=[d.arg(name='ipv6addresses', type=d.T.array)]),
  withIpv6AddressesMixin(ipv6addresses): { Properties+: { Ipv6Addresses+: ipv6addresses } },
  '#withKernelId':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-kernelid', args=[d.arg(name='kernelId', type=d.T.string)]),
  withKernelId(kernelId): { Properties+: { KernelId: kernelId } },
  '#withKeyName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-keyname', args=[d.arg(name='keyName', type=d.T.string)]),
  withKeyName(keyName): { Properties+: { KeyName: keyName } },
  '#withLaunchTemplate':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-launchtemplate', args=[d.arg(name='launchTemplate', type=d.T.object)]),
  withLaunchTemplate(launchTemplate): { Properties+: { LaunchTemplate: launchTemplate } },
  '#withLaunchTemplateMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-launchtemplate', args=[d.arg(name='launchTemplate', type=d.T.object)]),
  withLaunchTemplateMixin(launchTemplate): { Properties+: { LaunchTemplate+: launchTemplate } },
  '#withLicenseSpecifications':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-licensespecifications', args=[d.arg(name='licenseSpecifications', type=d.T.array)]),
  withLicenseSpecifications(licenseSpecifications): { Properties+: { LicenseSpecifications: licenseSpecifications } },
  '#withLicenseSpecificationsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-licensespecifications', args=[d.arg(name='licenseSpecifications', type=d.T.array)]),
  withLicenseSpecificationsMixin(licenseSpecifications): { Properties+: { LicenseSpecifications+: licenseSpecifications } },
  '#withMonitoring':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-monitoring', args=[d.arg(name='monitoring', type=d.T.bool)]),
  withMonitoring(monitoring): { Properties+: { Monitoring: monitoring } },
  '#withNetworkInterfaces':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-networkinterfaces', args=[d.arg(name='networkInterfaces', type=d.T.array)]),
  withNetworkInterfaces(networkInterfaces): { Properties+: { NetworkInterfaces: networkInterfaces } },
  '#withNetworkInterfacesMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-networkinterfaces', args=[d.arg(name='networkInterfaces', type=d.T.array)]),
  withNetworkInterfacesMixin(networkInterfaces): { Properties+: { NetworkInterfaces+: networkInterfaces } },
  '#withPlacementGroupName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-placementgroupname', args=[d.arg(name='placementGroupName', type=d.T.string)]),
  withPlacementGroupName(placementGroupName): { Properties+: { PlacementGroupName: placementGroupName } },
  '#withPrivateDnsNameOptions':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-privatednsnameoptions', args=[d.arg(name='privateDnsNameOptions', type=d.T.object)]),
  withPrivateDnsNameOptions(privateDnsNameOptions): { Properties+: { PrivateDnsNameOptions: privateDnsNameOptions } },
  '#withPrivateDnsNameOptionsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-privatednsnameoptions', args=[d.arg(name='privateDnsNameOptions', type=d.T.object)]),
  withPrivateDnsNameOptionsMixin(privateDnsNameOptions): { Properties+: { PrivateDnsNameOptions+: privateDnsNameOptions } },
  '#withPrivateIpAddress':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-privateipaddress', args=[d.arg(name='privateIpAddress', type=d.T.string)]),
  withPrivateIpAddress(privateIpAddress): { Properties+: { PrivateIpAddress: privateIpAddress } },
  '#withPropagateTagsToVolumeOnCreation':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-propagatetagstovolumeoncreation', args=[d.arg(name='propagateTagsToVolumeOnCreation', type=d.T.bool)]),
  withPropagateTagsToVolumeOnCreation(propagateTagsToVolumeOnCreation): { Properties+: { PropagateTagsToVolumeOnCreation: propagateTagsToVolumeOnCreation } },
  '#withRamdiskId':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-ramdiskid', args=[d.arg(name='ramdiskId', type=d.T.string)]),
  withRamdiskId(ramdiskId): { Properties+: { RamdiskId: ramdiskId } },
  '#withSecurityGroupIds':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-securitygroupids', args=[d.arg(name='securityGroupIds', type=d.T.array)]),
  withSecurityGroupIds(securityGroupIds): { Properties+: { SecurityGroupIds: securityGroupIds } },
  '#withSecurityGroupIdsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-securitygroupids', args=[d.arg(name='securityGroupIds', type=d.T.array)]),
  withSecurityGroupIdsMixin(securityGroupIds): { Properties+: { SecurityGroupIds+: securityGroupIds } },
  '#withSecurityGroups':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-securitygroups', args=[d.arg(name='securityGroups', type=d.T.array)]),
  withSecurityGroups(securityGroups): { Properties+: { SecurityGroups: securityGroups } },
  '#withSecurityGroupsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-securitygroups', args=[d.arg(name='securityGroups', type=d.T.array)]),
  withSecurityGroupsMixin(securityGroups): { Properties+: { SecurityGroups+: securityGroups } },
  '#withSourceDestCheck':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-sourcedestcheck', args=[d.arg(name='sourceDestCheck', type=d.T.bool)]),
  withSourceDestCheck(sourceDestCheck): { Properties+: { SourceDestCheck: sourceDestCheck } },
  '#withSsmAssociations':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-ssmassociations', args=[d.arg(name='ssmAssociations', type=d.T.array)]),
  withSsmAssociations(ssmAssociations): { Properties+: { SsmAssociations: ssmAssociations } },
  '#withSsmAssociationsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-ssmassociations', args=[d.arg(name='ssmAssociations', type=d.T.array)]),
  withSsmAssociationsMixin(ssmAssociations): { Properties+: { SsmAssociations+: ssmAssociations } },
  '#withSubnetId':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-subnetid', args=[d.arg(name='subnetId', type=d.T.string)]),
  withSubnetId(subnetId): { Properties+: { SubnetId: subnetId } },
  '#withTags':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTags(tags): { Properties+: { Tags: tags } },
  '#withTagsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTagsMixin(tags): { Properties+: { Tags+: tags } },
  '#withTenancy':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-tenancy', args=[d.arg(name='tenancy', type=d.T.string)]),
  withTenancy(tenancy): { Properties+: { Tenancy: tenancy } },
  '#withUserData':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-userdata', args=[d.arg(name='userData', type=d.T.string)]),
  withUserData(userData): { Properties+: { UserData: userData } },
  '#withVolumes':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-volumes', args=[d.arg(name='volumes', type=d.T.array)]),
  withVolumes(volumes): { Properties+: { Volumes: volumes } },
  '#withVolumesMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-volumes', args=[d.arg(name='volumes', type=d.T.array)]),
  withVolumesMixin(volumes): { Properties+: { Volumes+: volumes } },
}
