{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='BudgetsAction', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-budgets-budgetsaction.html'),
  '#withActionThreshold':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-budgets-budgetsaction.html#cfn-budgets-budgetsaction-actionthreshold', args=[d.arg(name='actionThreshold', type=d.T.string)]),
  withActionThreshold(actionThreshold): { Properties+: { ActionThreshold: actionThreshold } },
  '#withActionType':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-budgets-budgetsaction.html#cfn-budgets-budgetsaction-actiontype', args=[d.arg(name='actionType', type=d.T.string)]),
  withActionType(actionType): { Properties+: { ActionType: actionType } },
  '#withApprovalModel':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-budgets-budgetsaction.html#cfn-budgets-budgetsaction-approvalmodel', args=[d.arg(name='approvalModel', type=d.T.string)]),
  withApprovalModel(approvalModel): { Properties+: { ApprovalModel: approvalModel } },
  '#withBudgetName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-budgets-budgetsaction.html#cfn-budgets-budgetsaction-budgetname', args=[d.arg(name='budgetName', type=d.T.string)]),
  withBudgetName(budgetName): { Properties+: { BudgetName: budgetName } },
  '#withDefinition':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-budgets-budgetsaction.html#cfn-budgets-budgetsaction-definition', args=[d.arg(name='definition', type=d.T.string)]),
  withDefinition(definition): { Properties+: { Definition: definition } },
  '#withExecutionRoleArn':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-budgets-budgetsaction.html#cfn-budgets-budgetsaction-executionrolearn', args=[d.arg(name='executionRoleArn', type=d.T.string)]),
  withExecutionRoleArn(executionRoleArn): { Properties+: { ExecutionRoleArn: executionRoleArn } },
  '#withNotificationType':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-budgets-budgetsaction.html#cfn-budgets-budgetsaction-notificationtype', args=[d.arg(name='notificationType', type=d.T.string)]),
  withNotificationType(notificationType): { Properties+: { NotificationType: notificationType } },
  '#withSubscribers':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-budgets-budgetsaction.html#cfn-budgets-budgetsaction-subscribers', args=[d.arg(name='subscribers', type=d.T.string)]),
  withSubscribers(subscribers): { Properties+: { Subscribers: subscribers } },
}
