(import '../../../extensions/attributes.libsonnet') + {
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='PackagingGroup', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediapackage-packaginggroup.html'),
  new(errorOnEmptyProp=true): { Type: 'AWS::MediaPackage::PackagingGroup', Properties: { Id: if errorOnEmptyProp then (error 'You need to define Id properties for AWS::MediaPackage::PackagingGroup resource') else null } },
  '#new':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediapackage-packaginggroup.html', args=[d.arg(name='errorOnEmptyProp', type=d.T.bool)]),
  '#withAuthorization':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediapackage-packaginggroup.html#cfn-mediapackage-packaginggroup-authorization', args=[d.arg(name='authorization', type=d.T.object)]),
  withAuthorization(authorization): { Properties+: { Authorization: authorization } },
  '#withAuthorizationMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediapackage-packaginggroup.html#cfn-mediapackage-packaginggroup-authorization', args=[d.arg(name='authorization', type=d.T.object)]),
  withAuthorizationMixin(authorization): { Properties+: { Authorization+: authorization } },
  '#withEgressAccessLogs':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediapackage-packaginggroup.html#cfn-mediapackage-packaginggroup-egressaccesslogs', args=[d.arg(name='egressAccessLogs', type=d.T.object)]),
  withEgressAccessLogs(egressAccessLogs): { Properties+: { EgressAccessLogs: egressAccessLogs } },
  '#withEgressAccessLogsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediapackage-packaginggroup.html#cfn-mediapackage-packaginggroup-egressaccesslogs', args=[d.arg(name='egressAccessLogs', type=d.T.object)]),
  withEgressAccessLogsMixin(egressAccessLogs): { Properties+: { EgressAccessLogs+: egressAccessLogs } },
  '#withId':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediapackage-packaginggroup.html#cfn-mediapackage-packaginggroup-id', args=[d.arg(name='id', type=d.T.string)]),
  withId(id): { Properties+: { Id: id } },
  '#withTags':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediapackage-packaginggroup.html#cfn-mediapackage-packaginggroup-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTags(tags): { Properties+: { Tags: tags } },
  '#withTagsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediapackage-packaginggroup.html#cfn-mediapackage-packaginggroup-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTagsMixin(tags): { Properties+: { Tags+: tags } },
}
