{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='AWS.QuickSight.DataSource', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-quicksight-datasource.html'),
  '#withAlternateDataSourceParameters':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-quicksight-datasource.html#cfn-quicksight-datasource-alternatedatasourceparameters', args=[d.arg(name='alternateDataSourceParameters', type=d.T.string)]),
  withAlternateDataSourceParameters(alternateDataSourceParameters): { Properties+: { AlternateDataSourceParameters: alternateDataSourceParameters } },
  '#withAwsAccountId':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-quicksight-datasource.html#cfn-quicksight-datasource-awsaccountid', args=[d.arg(name='awsAccountId', type=d.T.string)]),
  withAwsAccountId(awsAccountId): { Properties+: { AwsAccountId: awsAccountId } },
  '#withCredentials':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-quicksight-datasource.html#cfn-quicksight-datasource-credentials', args=[d.arg(name='credentials', type=d.T.string)]),
  withCredentials(credentials): { Properties+: { Credentials: credentials } },
  '#withDataSourceId':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-quicksight-datasource.html#cfn-quicksight-datasource-datasourceid', args=[d.arg(name='dataSourceId', type=d.T.string)]),
  withDataSourceId(dataSourceId): { Properties+: { DataSourceId: dataSourceId } },
  '#withDataSourceParameters':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-quicksight-datasource.html#cfn-quicksight-datasource-datasourceparameters', args=[d.arg(name='dataSourceParameters', type=d.T.string)]),
  withDataSourceParameters(dataSourceParameters): { Properties+: { DataSourceParameters: dataSourceParameters } },
  '#withErrorInfo':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-quicksight-datasource.html#cfn-quicksight-datasource-errorinfo', args=[d.arg(name='errorInfo', type=d.T.string)]),
  withErrorInfo(errorInfo): { Properties+: { ErrorInfo: errorInfo } },
  '#withName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-quicksight-datasource.html#cfn-quicksight-datasource-name', args=[d.arg(name='name', type=d.T.string)]),
  withName(name): { Properties+: { Name: name } },
  '#withPermissions':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-quicksight-datasource.html#cfn-quicksight-datasource-permissions', args=[d.arg(name='permissions', type=d.T.string)]),
  withPermissions(permissions): { Properties+: { Permissions: permissions } },
  '#withSslProperties':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-quicksight-datasource.html#cfn-quicksight-datasource-sslproperties', args=[d.arg(name='sslProperties', type=d.T.string)]),
  withSslProperties(sslProperties): { Properties+: { SslProperties: sslProperties } },
  '#withTags':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-quicksight-datasource.html#cfn-quicksight-datasource-tags', args=[d.arg(name='tags', type=d.T.string)]),
  withTags(tags): { Properties+: { Tags: tags } },
  '#withType':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-quicksight-datasource.html#cfn-quicksight-datasource-type', args=[d.arg(name='type', type=d.T.string)]),
  withType(type): { Properties+: { Type: type } },
  '#withVpcConnectionProperties':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-quicksight-datasource.html#cfn-quicksight-datasource-vpcconnectionproperties', args=[d.arg(name='vpcConnectionProperties', type=d.T.string)]),
  withVpcConnectionProperties(vpcConnectionProperties): { Properties+: { VpcConnectionProperties: vpcConnectionProperties } },
}
