(import '../../../extensions/attributes.libsonnet') + {
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='Certificate', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-transfer-certificate.html'),
  new(errorOnEmptyProp=true): { Type: 'AWS::Transfer::Certificate', Properties: { Usage: if errorOnEmptyProp then (error 'You need to define Usage properties for AWS::Transfer::Certificate resource') else null, Certificate: if errorOnEmptyProp then (error 'You need to define Certificate properties for AWS::Transfer::Certificate resource') else null } },
  '#new':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-transfer-certificate.html', args=[d.arg(name='errorOnEmptyProp', type=d.T.bool)]),
  '#withActiveDate':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-transfer-certificate.html#cfn-transfer-certificate-activedate', args=[d.arg(name='activeDate', type=d.T.string)]),
  withActiveDate(activeDate): { Properties+: { ActiveDate: activeDate } },
  '#withCertificate':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-transfer-certificate.html#cfn-transfer-certificate-certificate', args=[d.arg(name='certificate', type=d.T.string)]),
  withCertificate(certificate): { Properties+: { Certificate: certificate } },
  '#withCertificateChain':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-transfer-certificate.html#cfn-transfer-certificate-certificatechain', args=[d.arg(name='certificateChain', type=d.T.string)]),
  withCertificateChain(certificateChain): { Properties+: { CertificateChain: certificateChain } },
  '#withDescription':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-transfer-certificate.html#cfn-transfer-certificate-description', args=[d.arg(name='description', type=d.T.string)]),
  withDescription(description): { Properties+: { Description: description } },
  '#withInactiveDate':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-transfer-certificate.html#cfn-transfer-certificate-inactivedate', args=[d.arg(name='inactiveDate', type=d.T.string)]),
  withInactiveDate(inactiveDate): { Properties+: { InactiveDate: inactiveDate } },
  '#withPrivateKey':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-transfer-certificate.html#cfn-transfer-certificate-privatekey', args=[d.arg(name='privateKey', type=d.T.string)]),
  withPrivateKey(privateKey): { Properties+: { PrivateKey: privateKey } },
  '#withTags':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-transfer-certificate.html#cfn-transfer-certificate-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTags(tags): { Properties+: { Tags: tags } },
  '#withTagsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-transfer-certificate.html#cfn-transfer-certificate-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTagsMixin(tags): { Properties+: { Tags+: tags } },
  '#withUsage':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-transfer-certificate.html#cfn-transfer-certificate-usage', args=[d.arg(name='usage', type=d.T.string)]),
  withUsage(usage): { Properties+: { Usage: usage } },
}
