(import '../../../extensions/attributes.libsonnet') + {
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='Connector', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-transfer-connector.html'),
  new(errorOnEmptyProp=true): { Type: 'AWS::Transfer::Connector', Properties: { Url: if errorOnEmptyProp then (error 'You need to define Url properties for AWS::Transfer::Connector resource') else null, AccessRole: if errorOnEmptyProp then (error 'You need to define AccessRole properties for AWS::Transfer::Connector resource') else null, As2Config: if errorOnEmptyProp then (error 'You need to define As2Config properties for AWS::Transfer::Connector resource') else null } },
  '#new':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-transfer-connector.html', args=[d.arg(name='errorOnEmptyProp', type=d.T.bool)]),
  '#withAccessRole':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-transfer-connector.html#cfn-transfer-connector-accessrole', args=[d.arg(name='accessRole', type=d.T.string)]),
  withAccessRole(accessRole): { Properties+: { AccessRole: accessRole } },
  '#withAs2Config':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-transfer-connector.html#cfn-transfer-connector-as2config', args=[d.arg(name='as2config', type=d.T.object)]),
  withAs2Config(as2config): { Properties+: { As2Config: as2config } },
  '#withAs2ConfigMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-transfer-connector.html#cfn-transfer-connector-as2config', args=[d.arg(name='as2config', type=d.T.object)]),
  withAs2ConfigMixin(as2config): { Properties+: { As2Config+: as2config } },
  '#withLoggingRole':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-transfer-connector.html#cfn-transfer-connector-loggingrole', args=[d.arg(name='loggingRole', type=d.T.string)]),
  withLoggingRole(loggingRole): { Properties+: { LoggingRole: loggingRole } },
  '#withTags':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-transfer-connector.html#cfn-transfer-connector-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTags(tags): { Properties+: { Tags: tags } },
  '#withTagsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-transfer-connector.html#cfn-transfer-connector-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTagsMixin(tags): { Properties+: { Tags+: tags } },
  '#withUrl':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-transfer-connector.html#cfn-transfer-connector-url', args=[d.arg(name='url', type=d.T.string)]),
  withUrl(url): { Properties+: { Url: url } },
}
