(import '../../../extensions/attributes.libsonnet') + {
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='EventDataStore', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudtrail-eventdatastore.html'),
  new(errorOnEmptyProp=true): { Type: 'AWS::CloudTrail::EventDataStore', Properties: {} },
  '#new':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudtrail-eventdatastore.html', args=[d.arg(name='errorOnEmptyProp', type=d.T.bool)]),
  '#withAdvancedEventSelectors':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudtrail-eventdatastore.html#cfn-cloudtrail-eventdatastore-advancedeventselectors', args=[d.arg(name='advancedEventSelectors', type=d.T.array)]),
  withAdvancedEventSelectors(advancedEventSelectors): { Properties+: { AdvancedEventSelectors: advancedEventSelectors } },
  '#withAdvancedEventSelectorsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudtrail-eventdatastore.html#cfn-cloudtrail-eventdatastore-advancedeventselectors', args=[d.arg(name='advancedEventSelectors', type=d.T.array)]),
  withAdvancedEventSelectorsMixin(advancedEventSelectors): { Properties+: { AdvancedEventSelectors+: advancedEventSelectors } },
  '#withMultiRegionEnabled':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudtrail-eventdatastore.html#cfn-cloudtrail-eventdatastore-multiregionenabled', args=[d.arg(name='multiRegionEnabled', type=d.T.bool)]),
  withMultiRegionEnabled(multiRegionEnabled): { Properties+: { MultiRegionEnabled: multiRegionEnabled } },
  '#withName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudtrail-eventdatastore.html#cfn-cloudtrail-eventdatastore-name', args=[d.arg(name='name', type=d.T.string)]),
  withName(name): { Properties+: { Name: name } },
  '#withOrganizationEnabled':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudtrail-eventdatastore.html#cfn-cloudtrail-eventdatastore-organizationenabled', args=[d.arg(name='organizationEnabled', type=d.T.bool)]),
  withOrganizationEnabled(organizationEnabled): { Properties+: { OrganizationEnabled: organizationEnabled } },
  '#withRetentionPeriod':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudtrail-eventdatastore.html#cfn-cloudtrail-eventdatastore-retentionperiod', args=[d.arg(name='retentionPeriod', type=d.T.number)]),
  withRetentionPeriod(retentionPeriod): { Properties+: { RetentionPeriod: retentionPeriod } },
  '#withTags':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudtrail-eventdatastore.html#cfn-cloudtrail-eventdatastore-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTags(tags): { Properties+: { Tags: tags } },
  '#withTagsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudtrail-eventdatastore.html#cfn-cloudtrail-eventdatastore-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTagsMixin(tags): { Properties+: { Tags+: tags } },
  '#withTerminationProtectionEnabled':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudtrail-eventdatastore.html#cfn-cloudtrail-eventdatastore-terminationprotectionenabled', args=[d.arg(name='terminationProtectionEnabled', type=d.T.bool)]),
  withTerminationProtectionEnabled(terminationProtectionEnabled): { Properties+: { TerminationProtectionEnabled: terminationProtectionEnabled } },
}
