(import '../../../extensions/attributes.libsonnet') + {
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='Detector', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-frauddetector-detector.html'),
  new(errorOnEmptyProp=true): { Type: 'AWS::FraudDetector::Detector', Properties: { DetectorId: if errorOnEmptyProp then (error 'You need to define DetectorId properties for AWS::FraudDetector::Detector resource') else null, EventType: if errorOnEmptyProp then (error 'You need to define EventType properties for AWS::FraudDetector::Detector resource') else null, Rules: if errorOnEmptyProp then (error 'You need to define Rules properties for AWS::FraudDetector::Detector resource') else null } },
  '#new':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-frauddetector-detector.html', args=[d.arg(name='errorOnEmptyProp', type=d.T.bool)]),
  '#withAssociatedModels':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-frauddetector-detector.html#cfn-frauddetector-detector-associatedmodels', args=[d.arg(name='associatedModels', type=d.T.array)]),
  withAssociatedModels(associatedModels): { Properties+: { AssociatedModels: associatedModels } },
  '#withAssociatedModelsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-frauddetector-detector.html#cfn-frauddetector-detector-associatedmodels', args=[d.arg(name='associatedModels', type=d.T.array)]),
  withAssociatedModelsMixin(associatedModels): { Properties+: { AssociatedModels+: associatedModels } },
  '#withDescription':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-frauddetector-detector.html#cfn-frauddetector-detector-description', args=[d.arg(name='description', type=d.T.string)]),
  withDescription(description): { Properties+: { Description: description } },
  '#withDetectorId':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-frauddetector-detector.html#cfn-frauddetector-detector-detectorid', args=[d.arg(name='detectorId', type=d.T.string)]),
  withDetectorId(detectorId): { Properties+: { DetectorId: detectorId } },
  '#withDetectorVersionStatus':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-frauddetector-detector.html#cfn-frauddetector-detector-detectorversionstatus', args=[d.arg(name='detectorVersionStatus', type=d.T.string)]),
  withDetectorVersionStatus(detectorVersionStatus): { Properties+: { DetectorVersionStatus: detectorVersionStatus } },
  '#withEventType':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-frauddetector-detector.html#cfn-frauddetector-detector-eventtype', args=[d.arg(name='eventType', type=d.T.object)]),
  withEventType(eventType): { Properties+: { EventType: eventType } },
  '#withEventTypeMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-frauddetector-detector.html#cfn-frauddetector-detector-eventtype', args=[d.arg(name='eventType', type=d.T.object)]),
  withEventTypeMixin(eventType): { Properties+: { EventType+: eventType } },
  '#withRuleExecutionMode':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-frauddetector-detector.html#cfn-frauddetector-detector-ruleexecutionmode', args=[d.arg(name='ruleExecutionMode', type=d.T.string)]),
  withRuleExecutionMode(ruleExecutionMode): { Properties+: { RuleExecutionMode: ruleExecutionMode } },
  '#withRules':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-frauddetector-detector.html#cfn-frauddetector-detector-rules', args=[d.arg(name='rules', type=d.T.array)]),
  withRules(rules): { Properties+: { Rules: rules } },
  '#withRulesMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-frauddetector-detector.html#cfn-frauddetector-detector-rules', args=[d.arg(name='rules', type=d.T.array)]),
  withRulesMixin(rules): { Properties+: { Rules+: rules } },
  '#withTags':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-frauddetector-detector.html#cfn-frauddetector-detector-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTags(tags): { Properties+: { Tags: tags } },
  '#withTagsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-frauddetector-detector.html#cfn-frauddetector-detector-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTagsMixin(tags): { Properties+: { Tags+: tags } },
}
