(import '../../../extensions/attributes.libsonnet') + {
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='ProvisioningTemplate', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iot-provisioningtemplate.html'),
  new(errorOnEmptyProp=true): { Type: 'AWS::IoT::ProvisioningTemplate', Properties: { TemplateBody: if errorOnEmptyProp then (error 'You need to define TemplateBody properties for AWS::IoT::ProvisioningTemplate resource') else null, ProvisioningRoleArn: if errorOnEmptyProp then (error 'You need to define ProvisioningRoleArn properties for AWS::IoT::ProvisioningTemplate resource') else null } },
  '#new':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iot-provisioningtemplate.html', args=[d.arg(name='errorOnEmptyProp', type=d.T.bool)]),
  '#withDescription':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iot-provisioningtemplate.html#cfn-iot-provisioningtemplate-description', args=[d.arg(name='description', type=d.T.string)]),
  withDescription(description): { Properties+: { Description: description } },
  '#withEnabled':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iot-provisioningtemplate.html#cfn-iot-provisioningtemplate-enabled', args=[d.arg(name='enabled', type=d.T.bool)]),
  withEnabled(enabled): { Properties+: { Enabled: enabled } },
  '#withPreProvisioningHook':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iot-provisioningtemplate.html#cfn-iot-provisioningtemplate-preprovisioninghook', args=[d.arg(name='preProvisioningHook', type=d.T.object)]),
  withPreProvisioningHook(preProvisioningHook): { Properties+: { PreProvisioningHook: preProvisioningHook } },
  '#withPreProvisioningHookMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iot-provisioningtemplate.html#cfn-iot-provisioningtemplate-preprovisioninghook', args=[d.arg(name='preProvisioningHook', type=d.T.object)]),
  withPreProvisioningHookMixin(preProvisioningHook): { Properties+: { PreProvisioningHook+: preProvisioningHook } },
  '#withProvisioningRoleArn':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iot-provisioningtemplate.html#cfn-iot-provisioningtemplate-provisioningrolearn', args=[d.arg(name='provisioningRoleArn', type=d.T.string)]),
  withProvisioningRoleArn(provisioningRoleArn): { Properties+: { ProvisioningRoleArn: provisioningRoleArn } },
  '#withTags':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iot-provisioningtemplate.html#cfn-iot-provisioningtemplate-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTags(tags): { Properties+: { Tags: tags } },
  '#withTagsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iot-provisioningtemplate.html#cfn-iot-provisioningtemplate-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTagsMixin(tags): { Properties+: { Tags+: tags } },
  '#withTemplateBody':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iot-provisioningtemplate.html#cfn-iot-provisioningtemplate-templatebody', args=[d.arg(name='templateBody', type=d.T.string)]),
  withTemplateBody(templateBody): { Properties+: { TemplateBody: templateBody } },
  '#withTemplateName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iot-provisioningtemplate.html#cfn-iot-provisioningtemplate-templatename', args=[d.arg(name='templateName', type=d.T.string)]),
  withTemplateName(templateName): { Properties+: { TemplateName: templateName } },
}
