{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='DeploymentGroup', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentgroup.html'),
  new(): { Type: 'AWS::CodeDeploy::DeploymentGroup', Properties: { ApplicationName: (error 'You need to define ApplicationName properties for AWS::CodeDeploy::DeploymentGroup resource'), ServiceRoleArn: (error 'You need to define ServiceRoleArn properties for AWS::CodeDeploy::DeploymentGroup resource') } },
  '#new':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentgroup.html', args=[]),
  dependsOn(dependencies=[]): { DependsOn: dependencies },
  '#dependsOn':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-dependson.html', args=[d.arg(name='dependencies', type=d.T.array)]),
  dependsOnMixin(dependencies=[]): { DependsOn+: dependencies },
  '#dependsOnMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-dependson.html', args=[d.arg(name='dependencies', type=d.T.array)]),
  creationPolicy(policy={}): { CreationPolicy: policy },
  '#creationPolicy':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-creationpolicy.html', args=[d.arg(name='policy', type=d.T.object)]),
  creationPolicyMixin(policy={}): { CreationPolicy+: policy },
  '#creationPolicyMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-creationpolicy.html', args=[d.arg(name='policy', type=d.T.object)]),
  deletionPolicy(policy={}): { DeletionPolicy: policy },
  '#deletionPolicy':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html', args=[d.arg(name='policy', type=d.T.object)]),
  deletionPolicyMixin(policy={}): { DeletionPolicy+: policy },
  '#deletionPolicyMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html', args=[d.arg(name='policy', type=d.T.object)]),
  updatePolicy(policy={}): { UpdatePolicy: policy },
  '#updatePolicy':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatepolicy.html', args=[d.arg(name='policy', type=d.T.object)]),
  updatePolicyMixin(policy={}): { UpdatePolicy+: policy },
  '#updatePolicyMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatepolicy.html', args=[d.arg(name='policy', type=d.T.object)]),
  updateReplacePolicy(policy={}): { UpdateReplacePolicy: policy },
  '#updateReplacePolicy':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatereplacepolicy.html', args=[d.arg(name='policy', type=d.T.object)]),
  updateReplacePolicyMixin(policy={}): { UpdateReplacePolicy+: policy },
  '#updateReplacePolicyMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatereplacepolicy.html', args=[d.arg(name='policy', type=d.T.object)]),
  metadata(metadatas=[]): { Metadata: metadatas },
  '#metadata':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-metadata.html', args=[d.arg(name='metadatas', type=d.T.object)]),
  metadataMixin(metadatas=[]): { Metadata+: metadatas },
  '#metadataMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-metadata.html', args=[d.arg(name='metadatas', type=d.T.object)]),
  '#withAlarmConfiguration':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentgroup.html#cfn-codedeploy-deploymentgroup-alarmconfiguration', args=[d.arg(name='alarmConfiguration', type=d.T.object)]),
  withAlarmConfiguration(alarmConfiguration): { Properties+: { AlarmConfiguration: alarmConfiguration } },
  '#withAlarmConfigurationMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentgroup.html#cfn-codedeploy-deploymentgroup-alarmconfiguration', args=[d.arg(name='alarmConfiguration', type=d.T.object)]),
  withAlarmConfigurationMixin(alarmConfiguration): { Properties+: { AlarmConfiguration+: alarmConfiguration } },
  '#withApplicationName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentgroup.html#cfn-codedeploy-deploymentgroup-applicationname', args=[d.arg(name='applicationName', type=d.T.string)]),
  withApplicationName(applicationName): { Properties+: { ApplicationName: applicationName } },
  '#withAutoRollbackConfiguration':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentgroup.html#cfn-codedeploy-deploymentgroup-autorollbackconfiguration', args=[d.arg(name='autoRollbackConfiguration', type=d.T.object)]),
  withAutoRollbackConfiguration(autoRollbackConfiguration): { Properties+: { AutoRollbackConfiguration: autoRollbackConfiguration } },
  '#withAutoRollbackConfigurationMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentgroup.html#cfn-codedeploy-deploymentgroup-autorollbackconfiguration', args=[d.arg(name='autoRollbackConfiguration', type=d.T.object)]),
  withAutoRollbackConfigurationMixin(autoRollbackConfiguration): { Properties+: { AutoRollbackConfiguration+: autoRollbackConfiguration } },
  '#withAutoScalingGroups':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentgroup.html#cfn-codedeploy-deploymentgroup-autoscalinggroups', args=[d.arg(name='autoScalingGroups', type=d.T.array)]),
  withAutoScalingGroups(autoScalingGroups): { Properties+: { AutoScalingGroups: autoScalingGroups } },
  '#withAutoScalingGroupsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentgroup.html#cfn-codedeploy-deploymentgroup-autoscalinggroups', args=[d.arg(name='autoScalingGroups', type=d.T.array)]),
  withAutoScalingGroupsMixin(autoScalingGroups): { Properties+: { AutoScalingGroups+: autoScalingGroups } },
  '#withBlueGreenDeploymentConfiguration':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentgroup.html#cfn-codedeploy-deploymentgroup-bluegreendeploymentconfiguration', args=[d.arg(name='blueGreenDeploymentConfiguration', type=d.T.object)]),
  withBlueGreenDeploymentConfiguration(blueGreenDeploymentConfiguration): { Properties+: { BlueGreenDeploymentConfiguration: blueGreenDeploymentConfiguration } },
  '#withBlueGreenDeploymentConfigurationMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentgroup.html#cfn-codedeploy-deploymentgroup-bluegreendeploymentconfiguration', args=[d.arg(name='blueGreenDeploymentConfiguration', type=d.T.object)]),
  withBlueGreenDeploymentConfigurationMixin(blueGreenDeploymentConfiguration): { Properties+: { BlueGreenDeploymentConfiguration+: blueGreenDeploymentConfiguration } },
  '#withDeployment':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentgroup.html#cfn-codedeploy-deploymentgroup-deployment', args=[d.arg(name='deployment', type=d.T.object)]),
  withDeployment(deployment): { Properties+: { Deployment: deployment } },
  '#withDeploymentConfigName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentgroup.html#cfn-codedeploy-deploymentgroup-deploymentconfigname', args=[d.arg(name='deploymentConfigName', type=d.T.string)]),
  withDeploymentConfigName(deploymentConfigName): { Properties+: { DeploymentConfigName: deploymentConfigName } },
  '#withDeploymentGroupName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentgroup.html#cfn-codedeploy-deploymentgroup-deploymentgroupname', args=[d.arg(name='deploymentGroupName', type=d.T.string)]),
  withDeploymentGroupName(deploymentGroupName): { Properties+: { DeploymentGroupName: deploymentGroupName } },
  '#withDeploymentMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentgroup.html#cfn-codedeploy-deploymentgroup-deployment', args=[d.arg(name='deployment', type=d.T.object)]),
  withDeploymentMixin(deployment): { Properties+: { Deployment+: deployment } },
  '#withDeploymentStyle':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentgroup.html#cfn-codedeploy-deploymentgroup-deploymentstyle', args=[d.arg(name='deploymentStyle', type=d.T.object)]),
  withDeploymentStyle(deploymentStyle): { Properties+: { DeploymentStyle: deploymentStyle } },
  '#withDeploymentStyleMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentgroup.html#cfn-codedeploy-deploymentgroup-deploymentstyle', args=[d.arg(name='deploymentStyle', type=d.T.object)]),
  withDeploymentStyleMixin(deploymentStyle): { Properties+: { DeploymentStyle+: deploymentStyle } },
  '#withECSServices':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentgroup.html#cfn-codedeploy-deploymentgroup-ecsservices', args=[d.arg(name='ecsservices', type=d.T.array)]),
  withECSServices(ecsservices): { Properties+: { ECSServices: ecsservices } },
  '#withECSServicesMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentgroup.html#cfn-codedeploy-deploymentgroup-ecsservices', args=[d.arg(name='ecsservices', type=d.T.array)]),
  withECSServicesMixin(ecsservices): { Properties+: { ECSServices+: ecsservices } },
  '#withEc2TagFilters':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentgroup.html#cfn-codedeploy-deploymentgroup-ec2tagfilters', args=[d.arg(name='ec2tagFilters', type=d.T.array)]),
  withEc2TagFilters(ec2tagFilters): { Properties+: { Ec2TagFilters: ec2tagFilters } },
  '#withEc2TagFiltersMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentgroup.html#cfn-codedeploy-deploymentgroup-ec2tagfilters', args=[d.arg(name='ec2tagFilters', type=d.T.array)]),
  withEc2TagFiltersMixin(ec2tagFilters): { Properties+: { Ec2TagFilters+: ec2tagFilters } },
  '#withEc2TagSet':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentgroup.html#cfn-codedeploy-deploymentgroup-ec2tagset', args=[d.arg(name='ec2tagSet', type=d.T.object)]),
  withEc2TagSet(ec2tagSet): { Properties+: { Ec2TagSet: ec2tagSet } },
  '#withEc2TagSetMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentgroup.html#cfn-codedeploy-deploymentgroup-ec2tagset', args=[d.arg(name='ec2tagSet', type=d.T.object)]),
  withEc2TagSetMixin(ec2tagSet): { Properties+: { Ec2TagSet+: ec2tagSet } },
  '#withLoadBalancerInfo':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentgroup.html#cfn-codedeploy-deploymentgroup-loadbalancerinfo', args=[d.arg(name='loadBalancerInfo', type=d.T.object)]),
  withLoadBalancerInfo(loadBalancerInfo): { Properties+: { LoadBalancerInfo: loadBalancerInfo } },
  '#withLoadBalancerInfoMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentgroup.html#cfn-codedeploy-deploymentgroup-loadbalancerinfo', args=[d.arg(name='loadBalancerInfo', type=d.T.object)]),
  withLoadBalancerInfoMixin(loadBalancerInfo): { Properties+: { LoadBalancerInfo+: loadBalancerInfo } },
  '#withOnPremisesInstanceTagFilters':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentgroup.html#cfn-codedeploy-deploymentgroup-onpremisesinstancetagfilters', args=[d.arg(name='onPremisesInstanceTagFilters', type=d.T.array)]),
  withOnPremisesInstanceTagFilters(onPremisesInstanceTagFilters): { Properties+: { OnPremisesInstanceTagFilters: onPremisesInstanceTagFilters } },
  '#withOnPremisesInstanceTagFiltersMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentgroup.html#cfn-codedeploy-deploymentgroup-onpremisesinstancetagfilters', args=[d.arg(name='onPremisesInstanceTagFilters', type=d.T.array)]),
  withOnPremisesInstanceTagFiltersMixin(onPremisesInstanceTagFilters): { Properties+: { OnPremisesInstanceTagFilters+: onPremisesInstanceTagFilters } },
  '#withOnPremisesTagSet':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentgroup.html#cfn-codedeploy-deploymentgroup-onpremisestagset', args=[d.arg(name='onPremisesTagSet', type=d.T.object)]),
  withOnPremisesTagSet(onPremisesTagSet): { Properties+: { OnPremisesTagSet: onPremisesTagSet } },
  '#withOnPremisesTagSetMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentgroup.html#cfn-codedeploy-deploymentgroup-onpremisestagset', args=[d.arg(name='onPremisesTagSet', type=d.T.object)]),
  withOnPremisesTagSetMixin(onPremisesTagSet): { Properties+: { OnPremisesTagSet+: onPremisesTagSet } },
  '#withServiceRoleArn':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentgroup.html#cfn-codedeploy-deploymentgroup-servicerolearn', args=[d.arg(name='serviceRoleArn', type=d.T.string)]),
  withServiceRoleArn(serviceRoleArn): { Properties+: { ServiceRoleArn: serviceRoleArn } },
  '#withTriggerConfigurations':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentgroup.html#cfn-codedeploy-deploymentgroup-triggerconfigurations', args=[d.arg(name='triggerConfigurations', type=d.T.array)]),
  withTriggerConfigurations(triggerConfigurations): { Properties+: { TriggerConfigurations: triggerConfigurations } },
  '#withTriggerConfigurationsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentgroup.html#cfn-codedeploy-deploymentgroup-triggerconfigurations', args=[d.arg(name='triggerConfigurations', type=d.T.array)]),
  withTriggerConfigurationsMixin(triggerConfigurations): { Properties+: { TriggerConfigurations+: triggerConfigurations } },
}
