(import '../../../extensions/attributes.libsonnet') + {
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='VPC', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpc.html'),
  new(errorOnEmptyProp=true): { Type: 'AWS::EC2::VPC', Properties: {} },
  '#new':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpc.html', args=[d.arg(name='errorOnEmptyProp', type=d.T.bool)]),
  '#withCidrBlock':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpc.html#cfn-ec2-vpc-cidrblock', args=[d.arg(name='cidrBlock', type=d.T.string)]),
  withCidrBlock(cidrBlock): { Properties+: { CidrBlock: cidrBlock } },
  '#withEnableDnsHostnames':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpc.html#cfn-ec2-vpc-enablednshostnames', args=[d.arg(name='enableDnsHostnames', type=d.T.bool)]),
  withEnableDnsHostnames(enableDnsHostnames): { Properties+: { EnableDnsHostnames: enableDnsHostnames } },
  '#withEnableDnsSupport':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpc.html#cfn-ec2-vpc-enablednssupport', args=[d.arg(name='enableDnsSupport', type=d.T.bool)]),
  withEnableDnsSupport(enableDnsSupport): { Properties+: { EnableDnsSupport: enableDnsSupport } },
  '#withInstanceTenancy':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpc.html#cfn-ec2-vpc-instancetenancy', args=[d.arg(name='instanceTenancy', type=d.T.string)]),
  withInstanceTenancy(instanceTenancy): { Properties+: { InstanceTenancy: instanceTenancy } },
  '#withIpv4IpamPoolId':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpc.html#cfn-ec2-vpc-ipv4ipampoolid', args=[d.arg(name='ipv4ipamPoolId', type=d.T.string)]),
  withIpv4IpamPoolId(ipv4ipamPoolId): { Properties+: { Ipv4IpamPoolId: ipv4ipamPoolId } },
  '#withIpv4NetmaskLength':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpc.html#cfn-ec2-vpc-ipv4netmasklength', args=[d.arg(name='ipv4netmaskLength', type=d.T.number)]),
  withIpv4NetmaskLength(ipv4netmaskLength): { Properties+: { Ipv4NetmaskLength: ipv4netmaskLength } },
  '#withTags':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpc.html#cfn-ec2-vpc-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTags(tags): { Properties+: { Tags: tags } },
  '#withTagsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpc.html#cfn-ec2-vpc-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTagsMixin(tags): { Properties+: { Tags+: tags } },
}
