(import '../../../extensions/attributes.libsonnet') + {
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='MissionProfile', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-groundstation-missionprofile.html'),
  new(errorOnEmptyProp=true): { Type: 'AWS::GroundStation::MissionProfile', Properties: { Name: if errorOnEmptyProp then (error 'You need to define Name properties for AWS::GroundStation::MissionProfile resource') else null, MinimumViableContactDurationSeconds: if errorOnEmptyProp then (error 'You need to define MinimumViableContactDurationSeconds properties for AWS::GroundStation::MissionProfile resource') else null, DataflowEdges: if errorOnEmptyProp then (error 'You need to define DataflowEdges properties for AWS::GroundStation::MissionProfile resource') else null, TrackingConfigArn: if errorOnEmptyProp then (error 'You need to define TrackingConfigArn properties for AWS::GroundStation::MissionProfile resource') else null } },
  '#new':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-groundstation-missionprofile.html', args=[d.arg(name='errorOnEmptyProp', type=d.T.bool)]),
  '#withContactPostPassDurationSeconds':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-groundstation-missionprofile.html#cfn-groundstation-missionprofile-contactpostpassdurationseconds', args=[d.arg(name='contactPostPassDurationSeconds', type=d.T.number)]),
  withContactPostPassDurationSeconds(contactPostPassDurationSeconds): { Properties+: { ContactPostPassDurationSeconds: contactPostPassDurationSeconds } },
  '#withContactPrePassDurationSeconds':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-groundstation-missionprofile.html#cfn-groundstation-missionprofile-contactprepassdurationseconds', args=[d.arg(name='contactPrePassDurationSeconds', type=d.T.number)]),
  withContactPrePassDurationSeconds(contactPrePassDurationSeconds): { Properties+: { ContactPrePassDurationSeconds: contactPrePassDurationSeconds } },
  '#withDataflowEdges':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-groundstation-missionprofile.html#cfn-groundstation-missionprofile-dataflowedges', args=[d.arg(name='dataflowEdges', type=d.T.array)]),
  withDataflowEdges(dataflowEdges): { Properties+: { DataflowEdges: dataflowEdges } },
  '#withDataflowEdgesMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-groundstation-missionprofile.html#cfn-groundstation-missionprofile-dataflowedges', args=[d.arg(name='dataflowEdges', type=d.T.array)]),
  withDataflowEdgesMixin(dataflowEdges): { Properties+: { DataflowEdges+: dataflowEdges } },
  '#withMinimumViableContactDurationSeconds':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-groundstation-missionprofile.html#cfn-groundstation-missionprofile-minimumviablecontactdurationseconds', args=[d.arg(name='minimumViableContactDurationSeconds', type=d.T.number)]),
  withMinimumViableContactDurationSeconds(minimumViableContactDurationSeconds): { Properties+: { MinimumViableContactDurationSeconds: minimumViableContactDurationSeconds } },
  '#withName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-groundstation-missionprofile.html#cfn-groundstation-missionprofile-name', args=[d.arg(name='name', type=d.T.string)]),
  withName(name): { Properties+: { Name: name } },
  '#withTags':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-groundstation-missionprofile.html#cfn-groundstation-missionprofile-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTags(tags): { Properties+: { Tags: tags } },
  '#withTagsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-groundstation-missionprofile.html#cfn-groundstation-missionprofile-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTagsMixin(tags): { Properties+: { Tags+: tags } },
  '#withTrackingConfigArn':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-groundstation-missionprofile.html#cfn-groundstation-missionprofile-trackingconfigarn', args=[d.arg(name='trackingConfigArn', type=d.T.string)]),
  withTrackingConfigArn(trackingConfigArn): { Properties+: { TrackingConfigArn: trackingConfigArn } },
}
