(import '../../../extensions/attributes.libsonnet') + {
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='Pipeline', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-pipeline.html'),
  new(errorOnEmptyProp=true): { Type: 'AWS::SageMaker::Pipeline', Properties: { RoleArn: if errorOnEmptyProp then (error 'You need to define RoleArn properties for AWS::SageMaker::Pipeline resource') else null, PipelineDefinition: if errorOnEmptyProp then (error 'You need to define PipelineDefinition properties for AWS::SageMaker::Pipeline resource') else null, PipelineName: if errorOnEmptyProp then (error 'You need to define PipelineName properties for AWS::SageMaker::Pipeline resource') else null } },
  '#new':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-pipeline.html', args=[d.arg(name='errorOnEmptyProp', type=d.T.bool)]),
  '#withParallelismConfiguration':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-pipeline.html#cfn-sagemaker-pipeline-parallelismconfiguration', args=[d.arg(name='parallelismConfiguration', type=d.T.object)]),
  withParallelismConfiguration(parallelismConfiguration): { Properties+: { ParallelismConfiguration: parallelismConfiguration } },
  '#withParallelismConfigurationMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-pipeline.html#cfn-sagemaker-pipeline-parallelismconfiguration', args=[d.arg(name='parallelismConfiguration', type=d.T.object)]),
  withParallelismConfigurationMixin(parallelismConfiguration): { Properties+: { ParallelismConfiguration+: parallelismConfiguration } },
  '#withPipelineDefinition':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-pipeline.html#cfn-sagemaker-pipeline-pipelinedefinition', args=[d.arg(name='pipelineDefinition', type=d.T.object)]),
  withPipelineDefinition(pipelineDefinition): { Properties+: { PipelineDefinition: pipelineDefinition } },
  '#withPipelineDefinitionMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-pipeline.html#cfn-sagemaker-pipeline-pipelinedefinition', args=[d.arg(name='pipelineDefinition', type=d.T.object)]),
  withPipelineDefinitionMixin(pipelineDefinition): { Properties+: { PipelineDefinition+: pipelineDefinition } },
  '#withPipelineDescription':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-pipeline.html#cfn-sagemaker-pipeline-pipelinedescription', args=[d.arg(name='pipelineDescription', type=d.T.string)]),
  withPipelineDescription(pipelineDescription): { Properties+: { PipelineDescription: pipelineDescription } },
  '#withPipelineDisplayName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-pipeline.html#cfn-sagemaker-pipeline-pipelinedisplayname', args=[d.arg(name='pipelineDisplayName', type=d.T.string)]),
  withPipelineDisplayName(pipelineDisplayName): { Properties+: { PipelineDisplayName: pipelineDisplayName } },
  '#withPipelineName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-pipeline.html#cfn-sagemaker-pipeline-pipelinename', args=[d.arg(name='pipelineName', type=d.T.string)]),
  withPipelineName(pipelineName): { Properties+: { PipelineName: pipelineName } },
  '#withRoleArn':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-pipeline.html#cfn-sagemaker-pipeline-rolearn', args=[d.arg(name='roleArn', type=d.T.string)]),
  withRoleArn(roleArn): { Properties+: { RoleArn: roleArn } },
  '#withTags':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-pipeline.html#cfn-sagemaker-pipeline-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTags(tags): { Properties+: { Tags: tags } },
  '#withTagsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-pipeline.html#cfn-sagemaker-pipeline-tags', args=[d.arg(name='tags', type=d.T.array)]),
  withTagsMixin(tags): { Properties+: { Tags+: tags } },
}
