{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='AWS.ApplicationInsights.Application', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-applicationinsights-application.html'),
  '#withAutoConfigurationEnabled':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-applicationinsights-application.html#cfn-applicationinsights-application-autoconfigurationenabled', args=[d.arg(name='autoConfigurationEnabled', type=d.T.string)]),
  withAutoConfigurationEnabled(autoConfigurationEnabled): { Properties+: { AutoConfigurationEnabled: autoConfigurationEnabled } },
  '#withCWEMonitorEnabled':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-applicationinsights-application.html#cfn-applicationinsights-application-cwemonitorenabled', args=[d.arg(name='cwemonitorEnabled', type=d.T.string)]),
  withCWEMonitorEnabled(cwemonitorEnabled): { Properties+: { CWEMonitorEnabled: cwemonitorEnabled } },
  '#withComponentMonitoringSettings':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-applicationinsights-application.html#cfn-applicationinsights-application-componentmonitoringsettings', args=[d.arg(name='componentMonitoringSettings', type=d.T.string)]),
  withComponentMonitoringSettings(componentMonitoringSettings): { Properties+: { ComponentMonitoringSettings: componentMonitoringSettings } },
  '#withCustomComponents':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-applicationinsights-application.html#cfn-applicationinsights-application-customcomponents', args=[d.arg(name='customComponents', type=d.T.string)]),
  withCustomComponents(customComponents): { Properties+: { CustomComponents: customComponents } },
  '#withLogPatternSets':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-applicationinsights-application.html#cfn-applicationinsights-application-logpatternsets', args=[d.arg(name='logPatternSets', type=d.T.string)]),
  withLogPatternSets(logPatternSets): { Properties+: { LogPatternSets: logPatternSets } },
  '#withOpsCenterEnabled':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-applicationinsights-application.html#cfn-applicationinsights-application-opscenterenabled', args=[d.arg(name='opsCenterEnabled', type=d.T.string)]),
  withOpsCenterEnabled(opsCenterEnabled): { Properties+: { OpsCenterEnabled: opsCenterEnabled } },
  '#withOpsItemSNSTopicArn':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-applicationinsights-application.html#cfn-applicationinsights-application-opsitemsnstopicarn', args=[d.arg(name='opsItemSnstopicArn', type=d.T.string)]),
  withOpsItemSNSTopicArn(opsItemSnstopicArn): { Properties+: { OpsItemSNSTopicArn: opsItemSnstopicArn } },
  '#withResourceGroupName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-applicationinsights-application.html#cfn-applicationinsights-application-resourcegroupname', args=[d.arg(name='resourceGroupName', type=d.T.string)]),
  withResourceGroupName(resourceGroupName): { Properties+: { ResourceGroupName: resourceGroupName } },
  '#withTags':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-applicationinsights-application.html#cfn-applicationinsights-application-tags', args=[d.arg(name='tags', type=d.T.string)]),
  withTags(tags): { Properties+: { Tags: tags } },
}
