(import '../../../extensions/attributes.libsonnet') + {
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='App', url='', help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opsworks-app.html'),
  new(errorOnEmptyProp=true): { Type: 'AWS::OpsWorks::App', Properties: { StackId: if errorOnEmptyProp then (error 'You need to define StackId properties for AWS::OpsWorks::App resource') else null, Name: if errorOnEmptyProp then (error 'You need to define Name properties for AWS::OpsWorks::App resource') else null, Type: if errorOnEmptyProp then (error 'You need to define Type properties for AWS::OpsWorks::App resource') else null } },
  '#new':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opsworks-app.html', args=[d.arg(name='errorOnEmptyProp', type=d.T.bool)]),
  '#withAppSource':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opsworks-app.html#cfn-opsworks-app-appsource', args=[d.arg(name='appSource', type=d.T.object)]),
  withAppSource(appSource): { Properties+: { AppSource: appSource } },
  '#withAppSourceMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opsworks-app.html#cfn-opsworks-app-appsource', args=[d.arg(name='appSource', type=d.T.object)]),
  withAppSourceMixin(appSource): { Properties+: { AppSource+: appSource } },
  '#withAttributes':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opsworks-app.html#cfn-opsworks-app-attributes', args=[d.arg(name='attributes', type=d.T.object)]),
  withAttributes(attributes): { Properties+: { Attributes: attributes } },
  '#withAttributesMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opsworks-app.html#cfn-opsworks-app-attributes', args=[d.arg(name='attributes', type=d.T.object)]),
  withAttributesMixin(attributes): { Properties+: { Attributes+: attributes } },
  '#withDataSources':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opsworks-app.html#cfn-opsworks-app-datasources', args=[d.arg(name='dataSources', type=d.T.array)]),
  withDataSources(dataSources): { Properties+: { DataSources: dataSources } },
  '#withDataSourcesMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opsworks-app.html#cfn-opsworks-app-datasources', args=[d.arg(name='dataSources', type=d.T.array)]),
  withDataSourcesMixin(dataSources): { Properties+: { DataSources+: dataSources } },
  '#withDescription':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opsworks-app.html#cfn-opsworks-app-description', args=[d.arg(name='description', type=d.T.string)]),
  withDescription(description): { Properties+: { Description: description } },
  '#withDomains':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opsworks-app.html#cfn-opsworks-app-domains', args=[d.arg(name='domains', type=d.T.array)]),
  withDomains(domains): { Properties+: { Domains: domains } },
  '#withDomainsMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opsworks-app.html#cfn-opsworks-app-domains', args=[d.arg(name='domains', type=d.T.array)]),
  withDomainsMixin(domains): { Properties+: { Domains+: domains } },
  '#withEnableSsl':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opsworks-app.html#cfn-opsworks-app-enablessl', args=[d.arg(name='enableSsl', type=d.T.bool)]),
  withEnableSsl(enableSsl): { Properties+: { EnableSsl: enableSsl } },
  '#withEnvironment':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opsworks-app.html#cfn-opsworks-app-environment', args=[d.arg(name='environment', type=d.T.array)]),
  withEnvironment(environment): { Properties+: { Environment: environment } },
  '#withEnvironmentMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opsworks-app.html#cfn-opsworks-app-environment', args=[d.arg(name='environment', type=d.T.array)]),
  withEnvironmentMixin(environment): { Properties+: { Environment+: environment } },
  '#withName':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opsworks-app.html#cfn-opsworks-app-name', args=[d.arg(name='name', type=d.T.string)]),
  withName(name): { Properties+: { Name: name } },
  '#withShortname':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opsworks-app.html#cfn-opsworks-app-shortname', args=[d.arg(name='shortname', type=d.T.string)]),
  withShortname(shortname): { Properties+: { Shortname: shortname } },
  '#withSslConfiguration':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opsworks-app.html#cfn-opsworks-app-sslconfiguration', args=[d.arg(name='sslConfiguration', type=d.T.object)]),
  withSslConfiguration(sslConfiguration): { Properties+: { SslConfiguration: sslConfiguration } },
  '#withSslConfigurationMixin':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opsworks-app.html#cfn-opsworks-app-sslconfiguration', args=[d.arg(name='sslConfiguration', type=d.T.object)]),
  withSslConfigurationMixin(sslConfiguration): { Properties+: { SslConfiguration+: sslConfiguration } },
  '#withStackId':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opsworks-app.html#cfn-opsworks-app-stackid', args=[d.arg(name='stackId', type=d.T.string)]),
  withStackId(stackId): { Properties+: { StackId: stackId } },
  '#withType':: d.fn(help='https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opsworks-app.html#cfn-opsworks-app-type', args=[d.arg(name='type', type=d.T.string)]),
  withType(type): { Properties+: { Type: type } },
}
